### ISSUE TITLE
Aura's temporal directories doesn't work well with AUR packages that require manual downloads.

### ISSUE THREAD

**Issue by jevonearth** [aurapm/aura#107]
Can't install the lweks package using aura. Lwks distribution package needs to be downloaded manually, as one is required to accept a license. 

Aura tells me to drop the lwks-11.1.H-amd64.deb file into directory /var/cache/pacman/pkg/lwks28175/lwks where 28175 appears to be the PID of aura, so next time I run the command, it looks in a new directory. I can't predict what the pid will be.

More comments on the lwks aur package here: https://aur.archlinux.org/packages/lwks/

Full output pasted below from aura:

```
aura >>= Continue? [Y/n] 
aura >>= Building `lwks`...
aura >>= Well, building `lwks` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
==> Manual download from www.lwks.com/betas-linux required.
-> Place lwks-11.1.H-amd64.deb in /var/cache/pacman/pkg/lwks28175/lwks
==> Making package: lwks 11.1.H-2 (Thu May 30 15:32:16 PDT 2013)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
==> ERROR: lwks-11.1.H-amd64.deb was not found in the build directory and is not a URL.
```

**Comment by fosskers** [comment]
`lwks` builds just fine now, so I'll be closing this.
