### ISSUE TITLE
List of AUR packages that don't build

### ISSUE THREAD

**Issue by fosskers** [aurapm/aura#14]
When you find a package that didn't build, please explain _how_ the building failed. Thank you!
Here they are:
### UNSOLVED (as of 2018 June)

*Currently there are no reported unbuildable packages with the `aura-1.5` branch.*

**Comment by vmassuchetto** [comment]
Please:

    $ sudo aura -A linux-pf-headers
    aura >>= The following are not AUR packages:
    linux-pf-headers

    $ wget -q "https://aur.archlinux.org/packages/linux-pf-headers/" -O - | grep "<title>"
        <title>AUR (en) - linux-pf-headers</title>

**Comment by fosskers** [comment]
What version of `aura` are you using, @vmassuchetto ?

**Comment by vmassuchetto** [comment]
Sorry. AURA Version 1.3.0.5

**Comment by flamusdiu** [comment]
@fosskers : 

```
$ sudo aura -As linux-pf-headers
aur/linux-pf-headers 3.19.3-1 (151)
    Header files and scripts for building modules for linux-pf kernel.
$ sudo aura -Ai linux-pf-headers
aura: Maybe.fromJust: Nothing
```

**Comment by fosskers** [comment]
This feels like Virtual Package business again.

**Comment by flamusdiu** [comment]
@fosskers oops, looks like linux-fs-headers is a virtual package. Part of `linux-pf'. You can find that out here https://aur.archlinux.org/packages/li/linux-pf/PKGBUILD =)

2.0 can't come soon enough to fix these issues. #patienceandallthingswillcome :)

**Comment by FSMaxB** [comment]
neovim-git does build, but it doesn't install. At the point where pacman asks if you want to install the package `[Y/n]` aura simply exits. I guess there's something that's still queued in stdin that then get's interpreted by pacman as me not wanting to install the package.

**Comment by flamusdiu** [comment]
@FSMaxB Most of this odd issues are due to either the bash parser or virtual packages. Hopefully, most of these will autofix when Aura 2.0 comes out.

**Comment by fosskers** [comment]
@FSMaxB that's actually a known `neovim` bug and has nothing to do with Aura.

**Comment by flamusdiu** [comment]
@fosskers oops ... =P can we just #blameFossers until 2.0? j/king

**Comment by fosskers** [comment]
That usually strategy doesn't apply here haha.

**Comment by flamusdiu** [comment]
@fosskers 8)

**Comment by FSMaxB** [comment]
Strange, I don't really get how this is a neovim bug. This works when installing the package manually after building with makepkg. Sorry for not responding, I was ignoring the aura repository on github, but that disabled notifications for responses to this post.

**Comment by flamusdiu** [comment]
@FSMaxB check here: https://github.com/aurapm/aura/issues/321

**Comment by FSMaxB** [comment]
Ah, ok. Then I have to wait I guess.

**Comment by flamusdiu** [comment]
@FSMaxB no worries. seems I forgot too about this one (I don't use this package either). =\

**Comment by fosskers** [comment]
@FSMaxB `neovim-git` just built for me. Go for it.

**Comment by FSMaxB** [comment]
Thanks for notifying me.

**Comment by simon04** [comment]
Building of `lib32-libxp` fails. It seems that the source file `libxp-1.0.3-1-i686.pkg.tar.xz` is tried being installed instead of the built `lib32-libxp-1.0.3-1-x86_64.pkg.tar.xz`.
```
$ sudo aura -A lib32-libxp
aura >>= Determining dependencies...
aura >>= AUR Packages:
lib32-libxp

aura >>= Continue? [Y/n] 
aura >>= Building `lib32-libxp`...
loading packages...
warning: libxp-1.0.3-1 is up to date -- reinstalling
error: failed to prepare transaction (package architecture is not valid)
:: package libxp-1.0.3-1-i686 does not have a valid architecture
```

**Comment by vendion** [comment]
It seems Aura doesn't like something about `aether-git` (https://aur4.archlinux.org/packages/aether-git/)

When aura trying to build it, aura exits with the following error

```
aura >>= Determining dependencies...
aura >>= AUR Packages:
aether-git

aura >>= Continue? [Y/n] 
aura >>= Building `aether-git`...
aura: fd:8: hGetContents: invalid argument (invalid byte sequence)
```

**Comment by flamusdiu** [comment]
@vendion check your language settings. Make sure you explicitly set them to use UTF-8.

**Comment by vendion** [comment]
@flamusdiu My locale is set to use UTF-8

```
╭─vendion@Baldr ~  
╰─➤  locale
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by fosskers** [comment]
This has happened before, and future updates should auto-fix it since they'll be reading files in a different way.

**Comment by joca-bt** [comment]
```sudo aura -A evopop-gtk-theme-git``` results in ```aura: Cannot decode byte '\x6e': Data.Text.Internal.Encoding.streamDecodeUtf8With: Invalid UTF-8 stream```

**Comment by fritz-k** [comment]
`python-protobuf3` (dependency of cura)
```
$ sudo aura -A cura
aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `python-protobuf3` could not be found. You may need to search for a package to satisfy it.

$ sudo aura -As python-protobuf3
aur/python-protobuf3 3.0.0_beta_1-2 (8)
    Python 3 bindings for Google Protocol Buffers
aur/python-protobuf3-git 802e184-1 (0)
    Python 3 bindings for Google Protocol Buffers

$ sudo aura -A python-protobuf3
aura >>= The following are not AUR packages:
python-protobuf3

aura >>= No valid packages specified.

$ sudo aura -Ai python-protobuf3
aura: Maybe.fromJust: Nothing
```

**Comment by erbridge** [comment]
```
$ sudo aura -A git-lfs
aura >>= Determining dependencies...
aura >>= AUR Packages:
git-lfs

aura >>= Continue? [Y/n] 
aura >>= Building `git-lfs`...
aura >>= Well, building `git-lfs` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
aura >>= Failed to obtain build scripts for `git-lfs`.
aura >>= Would you like to continue anyway? [Y/n] n
aura >>= Building failed.
```

**Comment by fosskers** [comment]
@erbridge You need to manually update to `aura-1.3.2.1`. A recent AUR api update broke the `aur` haskell package, on which `aura` depends.

**Comment by erbridge** [comment]
Ah, ok. That fixes the issue, thanks.

**Comment by adituv** [comment]
`libtinfo`.  I've just recompiled aura from git; version now shows as 1.3.2.1, so the above fix didn't work for me.  I'm going to try `aura-bin` now.

~~~
$ sudo aura -A haskell-stack
aura >>= Determining dependencies...
aura >>= AUR Packages:
haskell-stack
libtinfo

aura >>= Continue? [Y/n] 
aura >>= Building `libtinfo`...
aura >>= Well, building `libtinfo` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
aura >>= Failed to obtain build scripts for `libtinfo`.
aura >>= Would you like to continue anyway? [Y/n] n
aura >>= Building failed.
~~~

**Comment by s0r00t** [comment]
screencloud

Aura couldn't install it, so I built it manually. However, on each update, this happens : 
```
aura >>= Building `screencloud`...
loading packages...
warning: screencloud-1.2.0-1 is up to date -- reinstalling
error: '/var/cache/pacman/pkg/screencloud-1.2.0-2-x86_64.pkg.tar.xz': duplicate target
```

**Comment by fosskers** [comment]
When I built it, I got this: `error: '/var/cache/pacman/pkg/screencloud-1.2.0-1-64.pkg.tar.xz': duplicate target`

Notice the difference? This file here is actually a source file, as defined in the PKGBUILD. After building, `aura` copies files that match `.pkg.tar.xz` and tries to install them. For this file to be named in the same way as *built* packages is the cause of the problem here.

**Comment by skgsergio** [comment]
`android-sdk` fails with missing dependencies, don't know about `aura` internals but seems to be failing trying to read the depends when using multi-arch depends:

Current [`android-sdk`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=android-sdk) depends:
```
depends_x86_64=('java-environment' 'lib32-alsa-lib' 'lib32-openal'
  'lib32-libstdc++5' 'lib32-libxv' 'lib32-mesa' 'lib32-ncurses' 'lib32-sdl'
  'lib32-zlib' 'lib32-fontconfig' 'lib32-libpulse' 'swt')
depends_i686=('java-environment' 'alsa-lib' 'openal' 'libstdc++5' 'libxv' 'sdl'
              'ncurses' 'swt' 'zlib')
```

Full  output:
```
sconde@sycorax ~ $ sudo aura -Ax android-sdk
aura >>= Determining dependencies...
aura >>= AUR Packages:
android-sdk

aura >>= Continue? [Y/n] 
aura >>= Building `android-sdk`...
==> Making package: android-sdk 24.4.1-1 (Tue Nov 17 16:03:41 CET 2015)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> lib32-openal
  -> lib32-libstdc++5
  -> lib32-sdl
  -> swt
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
aura >>= Well, building `android-sdk` failed.
aura >>= Would you like to continue anyway? [Y/n] n
aura >>= Building failed.
```

**Comment by erbridge** [comment]
`unity-editor` always hangs up the download around 10mins in, during an update:

```
$ aura -Auakx
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
unity-editor : 5.1.0f3+2015091501-2 => 5.2.2f1+20151018-1

aura >>= `unity-editor` PKGBUILD is up to date.
aura >>= Determining dependencies...
aura >>= AUR Packages:
unity-editor

aura >>= Continue? [Y/n] 
aura >>= Building `unity-editor`...
==> Making package: unity-editor 5.2.2f1+20151018-1 (Sat  5 Dec 00:29:43 GMT 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading unity-editor-installer-5.2.2f1+20151018.sh...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 87  953M   87  832M    0     0  1344k      0  0:12:06  0:10:34  0:01:32 1461kcurl: (18) transfer closed with 125686557 bytes remaining to read
==> ERROR: Failure while downloading unity-editor-installer-5.2.2f1+20151018.sh
    Aborting...
aura >>= Well, building `unity-editor` failed.
aura >>= Would you like to continue anyway? [Y/n] 
```

**Comment by bb010g** [comment]
@erbridge What's `makepkg` do?

**Comment by erbridge** [comment]
Same problem. Raised the issue with the package maintainers.

**Comment by erbridge** [comment]
`mysql-connector-c++` doesn't install.

```
$ aura -Auakx
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
mysql-connector-c++ : 1.1.6-3 => 1.1.6-4

aura >>= The following are not AUR packages:
mysql-connector-c++

aura >>= No valid packages specified.
```

**Comment by fosskers** [comment]
Confirmed @erbridge , this is likely an issue with Aura's bash parser, which we are in the process of ripping out.

**Comment by wbthomason** [comment]
`xprintidle` fails to build.

```
aura >>= Building `xprintidle`...
aura >>= Well, building `xprintidle` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
==> ERROR: url should not be an array
```

**Comment by ke7ofi** [comment]
tribler:

    aura: fd:7: hGetContents: invalid argument (invalid byte sequence)

**Comment by fosskers** [comment]
@ke7ofi I was able to build `tribler` no problem.The issue your having is often caused by locale problems. Are you utf-8 all around?

**Comment by ke7ofi** [comment]
I've since figured that out. (Is it still considered a bug?) What do I need to set to en_us UTF-8 in order to make it work?

**Comment by fosskers** [comment]
@ke7ofi see [here](https://github.com/aurapm/aura/issues/78#issuecomment-22460726).

**Comment by ke7ofi** [comment]
@fosskers thanks, I'll go away and stop asking obnoxious questions. Are there any plans to make it work without a locale?

**Comment by fosskers** [comment]
lol not a problem, we're here to help. Yeah, this should go away once Aura 1.4 is released.

**Comment by erbridge** [comment]
```
$ aura -Aakx gitlab
aura >>= `gitlab` has no stored PKGBUILD yet.
aura >>= Determining dependencies...
aura: Prelude.head: empty list
```

**Comment by fosskers** [comment]
That is a PKGBUILD parsing problem, which will be fixed with Aura 1.4.

**Comment by biinari** [comment]
Looks to me like `mysql-connector-c++` failing could be due to needing url escaping in the aur api call.

This returns nothing:

```sh
aura -Ap mysql-connector-c++
```

But escaping the plus characters in the URL successfully fetches the PKGBUILD:

```sh
aura -Ap mysql-connector-c%2B%2B
```

**Comment by fosskers** [comment]
Hm, that used to work. That's for reporting this.

**Comment by marc0der** [comment]
I'm having some odd behaviour when upgrading packages from the AUR. Hope I'm not doing something stupid, but this does seem like a bug as it was working fine before.

    $ sudo aura -Ayua
    ::Synchronising package databases...
     core is up to date
     extra is up to date
     community is up to date
     multilib is up to date
    aura >>= Fetching package information...
    aura >>= Comparing package versions...
    aura >>= AUR Packages to upgrade:
    atom-editor : 1.5.4-1 => 1.6.0-1
    spotify : 1.0.23.93-2 => 1.0.25.127-1
    tor-browser-en : 5.5.3-1 => 5.5.4-1

    aura >>= The following are not AUR packages:
    atom-editor
    spotify
    tor-browser-en

    aura >>= No valid packages specified.

**Comment by skgsergio** [comment]
@marc0der that is different issue and its being discussed here: https://github.com/aurapm/aura/issues/404

**Comment by marc0der** [comment]
Cool, sorry. It was the wrong one yes.

**Comment by stef204** [comment]
[Here] (https://bbs.archlinux.org/viewtopic.php?pid=1576601#p1576601) is a problem with aura, when powerpill needs to be updated.

It seems when aura uses powerpill, trying to update powerpill and its dependencies with aura fails.
I struggled with this issue until I found the thread referred above and manually (not using aura) installed: powerpill, pyalpm, pm2ml, python3-xcgf, python3-xcpf

**Comment by matmo** [comment]
[qgis](https://aur.archlinux.org/packages/qgis/) fails to build, because the evaluation of `depends=(python2-{httplib2,jinja,markupsafe,owslib,pygments,dateutil,pytz,six})` fails:

```bash
The dependency `python2-httplib2python2-jinjapython2-markupsafepython2-owslibpython2-
pygmentspython2-dateutilpython2-pytzpython2-six` could not be found. 
You may need to search for a package to satisfy it.
```

**Comment by fosskers** [comment]
Thanks @matmo , Aura 1.4 will fix that.

**Comment by ranisalt** [comment]
I couldn't any telegram-desktop{,-light} because of a dep (that is in AUR!)

**Comment by fosskers** [comment]
@ranisalt Thanks for reporting.

**Comment by timofonic** [comment]
@ranisalt @fosskers Has it been fixed?

**Comment by fosskers** [comment]
@timofonic @ranisalt Yes and no. Dependendency solving for `telegram-desktop-patched` works now, but the actual building fails with:

```
==> Retrieving sources...
  -> Cloning tdesktop git repo...
Cloning into bare repository '/var/cache/pacman/pkg/telegram-desktop-patched18555/telegram-desktop-patched/tdesktop'...
remote: Counting objects: 55791, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 55791 (delta 1), reused 1 (delta 0), pack-reused 55785
Receiving objects: 100% (55791/55791), 114.22 MiB | 14.62 MiB/s, done.
Resolving deltas: 100% (45156/45156), done.
  -> Cloning patches git repo...
Cloning into bare repository '/var/cache/pacman/pkg/telegram-desktop-patched18555/telegram-desktop-patched/patches'...
remote: Internal server error
fatal: unable to access 'https://git.mel.vin/telegram_desktop/patches.git/': The requested URL returned error: 500
==> ERROR: Failure while downloading patches git repo
    Aborting...
aura >>= Well, building `telegram-desktop-patched` failed.
```
which has nothing to do with Aura, as far as I can tell.

**Comment by ranisalt** [comment]
Telegram source packages are a pain. I recommend downloading the binaries and installing to your home dir or using `telegram-desktop-bin`. On the other hand, I managed to compile and install `telegram-desktop-systemqt`.

**Comment by fosskers** [comment]
I've always used the `-bin` myself.

**Comment by goose121** [comment]
I'm having issues building `japser-stt-pocketsphinx`: 

    aura >>= Determining dependencies...
    aura: Prelude.head: empty list
