### ISSUE TITLE
Downgrade support via SVN

### ISSUE THREAD

**Issue by knrafto** [aurapm/aura#146]
The instructions [here](https://wiki.archlinux.org/index.php?title=Getting_PKGBUILDS_From_SVN) give a way to get old PKGBUILDS via SVN. It seems like it could be automated by Aura, especially for getting a package from a certain date.

**Comment by Ninja-Koala** [comment]
Maybe this could also be used to get up to date PKGBUILDS.
The rsync mirror that abs uses is sometimes a little bit behind.

**Comment by fosskers** [comment]
We're switching to git-based package fetching in Aura 1.4, currently being developed.

**Comment by Ninja-Koala** [comment]
That's very cool, looking forward
