### ISSUE TITLE
googleearth PKGBUILD parse problems on 32-bit Arch

### ISSUE THREAD

**Issue by hutou** [aurapm/aura#174]
Trying to install GoogleEarth on my 32bits Arch system with 
```
$ sudo aura -A google-earth
```
gives me the following error
```
aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `lib32-fontconfig` could not be found. You may need to search for a package to satisfy it.
```
aura or PKGBUILD culprit ?

Package googleearth correctly installed with 
```
sudo aura -A ld-lsb
yaourt -S google-earth
```
Separate install of ld-lsb was needed because, on first try, "yaourt -S google-earth" complained about lib32-glibc, dependency of ld-lsb

See comments on https://aur.archlinux.org/packages/google-earth/

**Comment by fosskers** [comment]
Fixed.
