### ISSUE TITLE
Issue with aura -M

### ISSUE THREAD

**Issue by Jiehong** [aurapm/aura#184]
Hello,

In order to try out the new options of aura, I wanted to give a try to "-M".

My understanding is that aura will synchronise ABS locally, and then build the given package from the PKGBUILD retreived.

Let's give it a try: (sorry, it's in French)

``` sh
# sudo aura -My emacs
aura >>= Synchroniser l'arbre ABS local? [Y/n] n
aura >>= Synchronisation de `emacs` dans l'arbre ABS local...
aura >>= Les éléments suivants ne sont pas des paquets:
emacs

aura >>= Détermination des dépendances en cours...
aura >>= Continuer? [Y/n] n
aura >>= Installation manuelle annulée.
```

No luck. I guess I need to precise the repository too then:

``` sh
$ sudo aura -My extra/emacs
aura >>= Synchroniser l'arbre ABS local? [Y/n] n
aura >>= Détermination des dépendances en cours...
aura >>= ABS Paquets:
extra/emacs

aura >>= Continuer? [Y/n] Y
aura: /var/cache/aura/pkgbuilds/extra/emacs.pb: openFile: does not exist (No such file or directory)
```

Well, first it's a little bit surprising to have to provide the repository name as well as the package name, but let's say it's ok.

What I don't understand, is that it does not work at all. I tried with both aura and aura-bin.

I checked, and "/var/cache/aura/pkgbuilds/extra/" doesn't exist (either if I say Yes or No at synchronising ABS.)
However, /var/cache/aura/pkgbuilds/ seems to contain *.pb only from AUR packages.

Could you please have a look at this behaviour?

**Comment by iskatu** [comment]
Just stumbled across the same bug. `sudo aura -Mxa core/linux` fails with:

```
aura: /var/cache/aura/pkgbuilds/core/linux.pb: openFile: does not exist (No such file or directory)
```

**Comment by udnaan** [comment]
This was caused by, at least in my case, due to there being no directory in /var/cache/aura/pkgbuilds. 

Manually creating that directory fixed that problem

**Comment by fosskers** [comment]
The aura PKGBUILD is supposed to create that directory, but some users have reported it doesn't.

**Comment by tgoodlet** [comment]
Had the same problem doing
```shell
>>> sudo aura -A xonsh
aura: /var/cache/aura/pkgbuilds/core/xonsh.pb: openFile: does not exist (No such file or directory)
```
@udnaan's fix solved it for me.
I didn't acquire or build from the `PKGBUILD` which does seem to do that step.
Rebuilding from that works well.

There should really be some instructions for doing an initial `makepkg` build in the github README especially since all the links are broken on the [AUR page](https://aur.archlinux.org/packages/aura-bin/).

**Comment by flamusdiu** [comment]
@goodboy: all the links on AUR are broken how?

**Comment by tgoodlet** [comment]
@flamusdiu I may have exaggerated. I guess just the tarball link is:
https://bitbucket.org/fosskers/aura/downloads/aura-1.3.4-.tar.gz

**Comment by fosskers** [comment]
The AUR software does this for security reasons. If you want the real tarball, you can use `aura -Aw` to get it.
