### ISSUE TITLE
buliding julia-git skips install confirmation

### ISSUE THREAD

**Issue by blaenk** [aurapm/aura#195]
It has happened three times now on separate occasions, when first installing it and then twice again when upgrading. When I install the `julia-git` package using aura, it'll go through the build process and everything will go along successfully, but when it finishes, it'll show me the prompt to "proceed with installation" and, without pressing anything, it'll dump me at the prompt, as if there were a lingering newline or something else in the input buffer or something, perhaps left over from the build process, in which case a flush after the build process/before the `pacman -U` might be in order? It's a complete shot in the dark guess.

I then have to `pacman -U` the built package in the cache.

I don't know if this is specific to aura, but I thought I'd mention it here anyways.

**Comment by fosskers** [comment]
I tried testing this again with our latest aura, but the `master` branch of Julia itself doesn't seem to be compiling.
