### ISSUE TITLE
aura cannot build package with subpackages (backintime and backintime-cli)

### ISSUE THREAD

**Issue by catalin-hritcu** [aurapm/aura#218]
I know that this is a stupid situation, but aura loops on a direct package self dependency. For instance

```
sudo aura -A backintime
```

gets stuck on "Determining dependencies..."

While this seems like a problem with the backintime package, I wish it was more graciously handled.

**Comment by catalin-hritcu** [comment]
For what it's worth, this still fails even after the `backintime` package (https://aur.archlinux.org/pkgbase/backintime/) got simplified: it now only has two subpackages: `backintime` and `backintime-cli`. The message is (so no more looping):
```
aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `backintime-cli` could not be found. You may need to search for a package to satisfy it.
```

**Comment by fosskers** [comment]
Thanks for reporting this. The message remains the same: this will fix itself. I ask only for your patience :)

**Comment by robdockins** [comment]
I'm experiencing the same issue; backintime still fails to install properly via aura.  Any workarounds while we wait for aura2?

**Comment by catalin-hritcu** [comment]
I'm using a little shell script
```
#!/bin/sh
cd ~/Temp
rm -f backintime.tar.gz
rm -dfr backintime
wget https://aur.archlinux.org/packages/ba/backintime/backintime.tar.gz
tar xzvf backintime.tar.gz 
cd backintime 
makepkg 
sudo pacman -U backintime-1.?.*-?-any.pkg.tar.xz backintime-cli-1.?.*-?-any.pkg.tar.xz
```

**Comment by fosskers** [comment]
`backintime` now builds on the `aura-1.5` branch.
