### ISSUE TITLE
Aura fails to detect update for chromium-pepper-flash (AUR)

### ISSUE THREAD

**Issue by sebadoom** [aurapm/aura#284]
Yaourt detects an update:

chromium-pepper-flash  14.0.0.145-1 -> 1:15.0.0.152-1

Aura does not. Might the leading "1:" have anything to do with this?

**Comment by fosskers** [comment]
This is a fault of the packager. Even using our newer lib `versions`, version numbers like this would still fail to compare properly. 

In cases like this one would need to build manually to get through the conflict, and after that things should be fine.
