### ISSUE TITLE
(non issue) Release question

### ISSUE THREAD

**Issue by Agamennon** [aurapm/aura#286]
I am a fan of aura on arch, but it seems some packages are not functioning on aura 1.3 like (backintime) it seems aura 2.0 will be fixing those issues, can you guys give us a progress report?
I know its ready when its ready, i would just like to know what are the pain points and what is holding it back, so perhaps i could lend a hand

great stuff guys!

**Comment by fosskers** [comment]
1.4 is our priority for the time being.
