### ISSUE TITLE
Aura2 name?

### ISSUE THREAD

**Issue by mrak** [aurapm/aura#291]
Apologies if this has been discussed elsewhere.

Does it still make sense to have `aur` in the name if aura is going to be a distribution-agnostic package manager?

I love the name `aura` for arch linux (excellent and punny choice). But the origins of the name may be lost in the context of other systems. I'll offer a silly choice to start the conversation:

`pmonad` ~ "pm" for package manager and, of course, monad for haskell. Could have the command be named `pm`. Also P for package + Monad similar to X + Monad

**Comment by fosskers** [comment]
Definitely keeping the Aura name.
