### ISSUE TITLE
Automatically create missing directories

### ISSUE THREAD

**Issue by wereHamster** [aurapm/aura#294]
I just compiled aura and tried to install `aws-cli`:

```
# aura -A --noconfirm aws-cli
aura >>= Determining dependencies...
aura >>= AUR Packages:
aws-cli
python-colorama-0.2.5
python-rsa-3.1.2

aura: /var/cache/aura/pkgbuilds/python-colorama-0.2.5.pb: openFile:
    does not exist (No such file or directory)
```

After manually creating the pkgbuilds directory (`mkdir -p /var/cache/aura/pkgbuilds`) the installation succeeded.

**Comment by fosskers** [comment]
Well, the result of installing the `aura-git` AUR package is the same as cloning it yourself, except that `aura-git` will create the directories for you. Aura1 is depretiated anyway, so I don't think we need to fix this.
