### ISSUE TITLE
makepkg 4.2.0 breaks "--asroot" parameter

### ISSUE THREAD

**Issue by razzintown** [aurapm/aura#301]
Installing any AUR package as root gives this error:
`makepkg: invalid option '--asroot'`

Pacman changelog:
https://projects.archlinux.org/pacman.git/tree/NEWS#n57

I found the affected aura code in this line:
https://github.com/aurapm/aura/blob/master/src/Aura/MakePkg.hs#L69

Workaround is to only run `sudo aura` without root.

**Comment by flamusdiu** [comment]
I don't think this is really a workaround more as the new way of doing it.
Make sense anyway since running as root could be bad.

**Comment by fosskers** [comment]
Okay I'm going to look into this.

**Comment by fosskers** [comment]
One now **must** use the `--builduser` option when building as the true root.
