### ISSUE TITLE
Unable to build lib32-libwebp

### ISSUE THREAD

**Issue by justin8** [aurapm/aura#304]
When trying to build lib32-sdl2_image, it reports:

The dependency `lib32-libwebp#*-}` could not be found. You may need to search for a package to satisfy it.

**Comment by fosskers** [comment]
That's Bashfoo killing Aura's bash parser. This will fix itself when Aura2 reads `.PKGINFO` instead.

**Comment by justin8** [comment]
Awesome. Thanks for the fast response.
