### ISSUE TITLE
Display downloading progress bar on `-A`

### ISSUE THREAD

**Issue by GutenYe** [aurapm/aura#305]
The source files in AUR are various, sometime it maybe very slow to download, It would be nice to see a downloading progress bar when using `$ aura -A <pkg>`.

The `makepkg` by default has a `curl` progress bar, and I loved it.

**Comment by GutenYe** [comment]
Sorry, I just found a `-x, --unsuppress` option in man page is for it. Great work, this aura tool :)

**Comment by fosskers** [comment]
Glad you like it!
