### ISSUE TITLE
Steam-native not building 

### ISSUE THREAD

**Issue by PGPereira** [aurapm/aura#307]
That's the error log.
==> Making package: steam-native 1.0.0.49-8 (Mon Mar  9 16:51:01 BRT 2015)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> lib32-libappindicator
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.

**Comment by flamusdiu** [comment]
That has to do with virtual packages. I believe. You may have to manually download the lib32-libappindicator using `aura -Aw lib32-libappindicator` and then untar + manually run `makepkg -i`. Then try that again. Until Aura 2.0, this will be happening with some packages.

**Comment by PGPereira** [comment]
Done, thank you.

**Comment by PGPereira** [comment]
When will aura2 hit the AUR?

**Comment by bb010g** [comment]
Soon™.

**Comment by flamusdiu** [comment]
@PGPereira : yeah what @bb010g said. Have patience and it will be great. This doesn't happen too often but an issue with how dependencies are figured out. However, with aura2 hits then all these will go away finally.

**Comment by PGPereira** [comment]
Ok, then.
