### ISSUE TITLE
AUR URL is broken in `aura -Ai`

### ISSUE THREAD

**Issue by ramonsnir** [aurapm/aura#309]
When calling `aura -Ai adminer` I receive in the output: `AUR URL : https://aur.archlinux.org/ad/adminer`, which is broken (should be `https://aur.archlinux.org/packages/adminer/`).

```
Name           : aura-bin
Version        : 1.3.0.4-1
```

**Comment by fosskers** [comment]
This is a problem with the `aur` haskell package, which I am going to fix.

**Comment by fosskers** [comment]
Fixed on `aura1` branch.

**Comment by fosskers** [comment]
Turns out it wasn't a problem with `haskell-aur` at all, but with `aura` itself.
