### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by amosonn** [aurapm/aura#310]
I ran aura, gave a Ctrl+C at the wrong place, and got this. It might, of course, be a pacman issue, but I thought it best to report here first.
[amos@arch_amos ~]% sudo aura -A xdrawchem
[sudo] password for amos: 
aura >>= Determining dependencies...
^C*** Error in `pacman': munmap_chunk(): invalid pointer: 0x0000000001582ac0 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x7198e)[0x7fdc984a598e]
/usr/lib/libc.so.6(+0x76dee)[0x7fdc984aadee]
/usr/lib/libalpm.so.9(+0x199af)[0x7fdc98a939af]
/usr/lib/libalpm.so.9(alpm_list_free_inner+0x2a)[0x7fdc98a82e8a]
/usr/lib/libalpm.so.9(+0x11657)[0x7fdc98a8b657]
/usr/lib/libalpm.so.9(+0x11679)[0x7fdc98a8b679]
/usr/lib/libalpm.so.9(alpm_unregister_all_syncdbs+0x3a)[0x7fdc98a8aeda]
/usr/lib/libalpm.so.9(alpm_release+0x38)[0x7fdc98a82dc8]
pacman[0x40c970]
pacman[0x40ca9a]
/usr/lib/libc.so.6(+0x33540)[0x7fdc98467540]
/usr/lib/libc.so.6(+0x775cb)[0x7fdc984ab5cb]
/usr/lib/libalpm.so.9(alpm_dep_free+0xc)[0x7fdc98a8cb5c]
/usr/lib/libalpm.so.9(alpm_list_free_inner+0x2a)[0x7fdc98a82e8a]
/usr/lib/libalpm.so.9(+0x19b3f)[0x7fdc98a93b3f]
/usr/lib/libalpm.so.9(alpm_list_free_inner+0x2a)[0x7fdc98a82e8a]
/usr/lib/libalpm.so.9(+0x11657)[0x7fdc98a8b657]
/usr/lib/libalpm.so.9(+0x11679)[0x7fdc98a8b679]
/usr/lib/libalpm.so.9(alpm_unregister_all_syncdbs+0x3a)[0x7fdc98a8aeda]
/usr/lib/libalpm.so.9(alpm_release+0x38)[0x7fdc98a82dc8]
pacman[0x40c970]
pacman[0x40ca9a]
/usr/lib/libc.so.6(+0x33540)[0x7fdc98467540]
/usr/lib/libc.so.6(mbrtowc+0x6b)[0x7fdc984d028b]
/usr/lib/libarchive.so.13(archive_wstring_append_from_mbs+0xc4)[0x7fdc9882cb24]
/usr/lib/libarchive.so.13(archive_mstring_get_wcs+0x54)[0x7fdc9882d354]
/usr/lib/libarchive.so.13(archive_entry_pathname_w+0x26)[0x7fdc987eb466]
/usr/lib/libarchive.so.13(+0x48330)[0x7fdc9881f330]
/usr/lib/libarchive.so.13(+0x489c9)[0x7fdc9881f9c9]
/usr/lib/libarchive.so.13(+0x1e7ba)[0x7fdc987f57ba]
/usr/lib/libarchive.so.13(+0x1e8fc)[0x7fdc987f58fc]
/usr/lib/libalpm.so.9(+0xe197)[0x7fdc98a88197]
/usr/lib/libalpm.so.9(+0x11749)[0x7fdc98a8b749]
/usr/lib/libalpm.so.9(+0x1185a)[0x7fdc98a8b85a]
pacman[0x40c3a9]
pacman[0x40fad4]
pacman[0x4063c4]
/usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7fdc98454800]
pacman[0x4077f9]
======= Memory map: ========
00400000-0041d000 r-xp 00000000 08:02 392834                             /usr/bin/pacman
0061c000-0061d000 r--p 0001c000 08:02 392834                             /usr/bin/pacman
0061d000-0061e000 rw-p 0001d000 08:02 392834                             /usr/bin/pacman
0152f000-0192f000 rw-p 00000000 00:00 0                                  [heap]
7fdc94ba5000-7fdc94bbb000 r-xp 00000000 08:02 394750                     /usr/lib/libgcc_s.so.1
7fdc94bbb000-7fdc94dba000 ---p 00016000 08:02 394750                     /usr/lib/libgcc_s.so.1
7fdc94dba000-7fdc94dbb000 rw-p 00015000 08:02 394750                     /usr/lib/libgcc_s.so.1
7fdc94dbb000-7fdc94dcf000 r-xp 00000000 08:02 407154                     /usr/lib/libresolv-2.21.so
7fdc94dcf000-7fdc94fce000 ---p 00014000 08:02 407154                     /usr/lib/libresolv-2.21.so
7fdc94fce000-7fdc94fcf000 r--p 00013000 08:02 407154                     /usr/lib/libresolv-2.21.so
7fdc94fcf000-7fdc94fd0000 rw-p 00014000 08:02 407154                     /usr/lib/libresolv-2.21.so
7fdc94fd0000-7fdc94fd2000 rw-p 00000000 00:00 0 
7fdc94fd2000-7fdc94fd5000 r-xp 00000000 08:02 449315                     /usr/lib/libkeyutils.so.1.5
7fdc94fd5000-7fdc951d4000 ---p 00003000 08:02 449315                     /usr/lib/libkeyutils.so.1.5
7fdc951d4000-7fdc951d5000 r--p 00002000 08:02 449315                     /usr/lib/libkeyutils.so.1.5
7fdc951d5000-7fdc951d6000 rw-p 00003000 08:02 449315                     /usr/lib/libkeyutils.so.1.5
7fdc951d6000-7fdc951e2000 r-xp 00000000 08:02 401217                     /usr/lib/libkrb5support.so.0.1
7fdc951e2000-7fdc953e1000 ---p 0000c000 08:02 401217                     /usr/lib/libkrb5support.so.0.1
7fdc953e1000-7fdc953e2000 r--p 0000b000 08:02 401217                     /usr/lib/libkrb5support.so.0.1
7fdc953e2000-7fdc953e3000 rw-p 0000c000 08:02 401217                     /usr/lib/libkrb5support.so.0.1
7fdc953e3000-7fdc953e5000 r-xp 00000000 08:02 409205                     /usr/lib/libdl-2.21.so
7fdc953e5000-7fdc955e5000 ---p 00002000 08:02 409205                     /usr/lib/libdl-2.21.so
7fdc955e5000-7fdc955e6000 r--p 00002000 08:02 409205                     /usr/lib/libdl-2.21.so
7fdc955e6000-7fdc955e7000 rw-p 00003000 08:02 409205                     /usr/lib/libdl-2.21.so
7fdc955e7000-7fdc955ff000 r-xp 00000000 08:02 408940                     /usr/lib/libpthread-2.21.so
7fdc955ff000-7fdc957fe000 ---p 00018000 08:02 408940                     /usr/lib/libpthread-2.21.so
7fdc957fe000-7fdc957ff000 r--p 00017000 08:02 408940                     /usr/lib/libpthread-2.21.so
7fdc957ff000-7fdc95800000 rw-p 00018000 08:02 408940                     /usr/lib/libpthread-2.21.so
7fdc95800000-7fdc95804000 rw-p 00000000 00:00 0 
7fdc95804000-7fdc95807000 r-xp 00000000 08:02 395732                     /usr/lib/libcom_err.so.2.1
7fdc95807000-7fdc95a06000 ---p 00003000 08:02 395732                     /usr/lib/libcom_err.so.2.1
7fdc95a06000-7fdc95a07000 r--p 00002000 08:02 395732                     /usr/lib/libcom_err.so.2.1
7fdc95a07000-7fdc95a08000 rw-p 00003000 08:02 395732                     /usr/lib/libcom_err.so.2.1
7fdc95a08000-7fdc95a37000 r-xp 00000000 08:02 401215                     /usr/lib/libk5crypto.so.3.1
7fdc95a37000-7fdc95c36000 ---p 0002f000 08:02 401215                     /usr/lib/libk5crypto.so.3.1
7fdc95c36000-7fdc95c39000 r--p 0002e000 08:02 401215                     /usr/lib/libk5crypto.so.3.1
7fdc95c39000-7fdc95c3a000 rw-p 00031000 08:02 401215                     /usr/lib/libk5crypto.so.3.1
7fdc95c3a000-7fdc95c3b000 rw-p 00000000 00:00 0 
7fdc95c3b000-7fdc95d10000 r-xp 00000000 08:02 401175                     /usr/lib/libkrb5.so.3.3
7fdc95d10000-7fdc95f0f000 ---p 000d5000 08:02 401175                     /usr/lib/libkrb5.so.3.3
7fdc95f0f000-7fdc95f1d000 r--p 000d4000 08:02 401175                     /usr/lib/libkrb5.so.3.3
7fdc95f1d000-7fdc95f20000 rw-p 000e2000 08:02 401175                     /usr/lib/libkrb5.so.3.3
7fdc95f20000-7fdc95f6a000 r-xp 00000000 08:02 401206                     /usr/lib/libgssapi_krb5.so.2.2
7fdc95f6a000-7fdc96169000 ---p 0004a000 08:02 401206                     /usr/lib/libgssapi_krb5.so.2.2
7fdc96169000-7fdc9616b000 r--p 00049000 08:02 401206                     /usr/lib/libgssapi_krb5.so.2.2
7fdc9616b000-7fdc9616d000 rw-p 0004b000 08:02 401206                     /usr/lib/libgssapi_krb5.so.2.2
7fdc9616d000-7fdc961db000 r-xp 00000000 08:02 446406                     /usr/lib/libssl.so.1.0.0
7fdc961db000-7fdc963da000 ---p 0006e000 08:02 446406                     /usr/lib/libssl.so.1.0.0
7fdc963da000-7fdc963df000 r--p 0006d000 08:02 446406                     /usr/lib/libssl.so.1.0.0
7fdc963df000-7fdc963e6000 rw-p 00072000 08:02 446406                     /usr/lib/libssl.so.1.0.0
7fdc963e6000-7fdc9640e000 r-xp 00000000 08:02 405015                     /usr/lib/libssh2.so.1.0.1
7fdc9640e000-7fdc9660d000 ---p 00028000 08:02 405015                     /usr/lib/libssh2.so.1.0.1
7fdc9660d000-7fdc9660e000 r--p 00027000 08:02 405015                     /usr/lib/libssh2.so.1.0.1
7fdc9660e000-7fdc9660f000 rw-p 00028000 08:02 405015                     /usr/lib/libssh2.so.1.0.1
7fdc9660f000-7fdc96641000 r-xp 00000000 08:02 396304                     /usr/lib/libidn.so.11.6.13
7fdc96641000-7fdc96841000 ---p 00032000 08:02 396304                     /usr/lib/libidn.so.11.6.13
7fdc96841000-7fdc96842000 r--p 00032000 08:02 396304                     /usr/lib/libidn.so.11.6.13
7fdc96842000-7fdc96843000 rw-p 00033000 08:02 396304                     /usr/lib/libidn.so.11.6.13
7fdc96843000-7fdc96854000 r-xp 00000000 08:02 421449                     /usr/lib/libgpg-error.so.0.14.0
7fdc96854000-7fdc96a53000 ---p 00011000 08:02 421449                     /usr/lib/libgpg-error.so.0.14.0
7fdc96a53000-7fdc96a54000 r--p 00010000 08:02 421449                     /usr/lib/libgpg-error.so.0.14.0
7fdc96a54000-7fdc96a55000 rw-p 00011000 08:02 421449                     /usr/lib/libgpg-error.so.0.14.0
7fdc96a55000-7fdc96a65000 r-xp 00000000 08:02 392221                     /usr/lib/libassuan.so.0.4.3
7fdc96a65000-7fdc96c65000 ---p 00010000 08:02 392221                     /usr/lib/libassuan.so.0.4.3
7fdc96c65000-7fdc96c66000 r--p 00010000 08:02 392221                     /usr/lib/libassuan.so.0.4.3
7fdc96c66000-7fdc96c67000 rw-p 00011000 08:02 392221                     /usr/lib/libassuan.so.0.4.3
7fdc96c67000-7fdc96c7c000 r-xp 00000000 08:02 400182                     /usr/lib/libz.so.1.2.8
7fdc96c7c000-7fdc96e7b000 ---p 00015000 08:02 400182                     /usr/lib/libz.so.1.2.8
7fdc96e7b000-7fdc96e7c000 r--p 00014000 08:02 400182                     /usr/lib/libz.so.1.2.8
7fdc96e7c000-7fdc96e7d000 rw-p 00015000 08:02 400182                     /usr/lib/libz.so.1.2.8
7fdc96e7d000-7fdc96e8c000 r-xp 00000000 08:02 402016                     /usr/lib/libbz2.so.1.0.6
7fdc96e8c000-7fdc9708b000 ---p 0000f000 08:02 402016                     /usr/lib/libbz2.so.1.0.6
7fdc9708b000-7fdc9708d000 rw-p 0000e000 08:02 402016                     /usr/lib/libbz2.so.1.0.6
7fdc9708d000-7fdc970b2000 r-xp 00000000 08:02 392525                     /usr/lib/liblzma.so.5.2.1
7fdc970b2000-7fdc972b1000 ---p 00025000 08:02 392525                     /usr/lib/liblzma.so.5.2.1
7fdc972b1000-7fdc972b2000 r--p 00024000 08:02 392525                     /usr/lib/liblzma.so.5.2.1
7fdc972b2000-7fdc972b3000 rw-p 00025000 08:02 392525                     /usr/lib/liblzma.so.5.2.1
7fdc972b3000-7fdc972d4000 r-xp 00000000 08:02 408348                     /usr/lib/liblzo2.so.2.0.0
7fdc972d4000-7fdc974d3000 ---p 00021000 08:02 408348                     /usr/lib/liblzo2.so.2.0.0
7fdc974d3000-7fdc974d4000 r--p 00020000 08:02 408348                     /usr/lib/liblzo2.so.2.0.0
7fdc974d4000-7fdc974d5000 rw-p 00021000 08:02 408348                     /usr/lib/liblzo2.so.2.0.0
7fdc974d5000-7fdc974fc000 r-xp 00000000 08:02 409775                     /usr/lib/libexpat.so.1.6.0
7fdc974fc000-7fdc976fb000 ---p 00027000 08:02 409775                     /usr/lib/libexpat.so.1.6.0
7fdc976fb000-7fdc976fe000 r--p 00026000 08:02 409775                     /usr/lib/libexpat.so.1.6.0
7fdc976fe000-7fdc976ff000 rw-p 00029000 08:02 409775                     /usr/lib/libexpat.so.1.6.0
7fdc976ff000-7fdc97703000 r-xp 00000000 08:02 412878                     /usr/lib/libattr.so.1.1.0
7fdc97703000-7fdc97902000 ---p 00004000 08:02 412878                     /usr/lib/libattr.so.1.1.0
7fdc97902000-7fdc97903000 r--p 00003000 08:02 412878                     /usr/lib/libattr.so.1.1.0
7fdc97903000-7fdc97904000 rw-p 00004000 08:02 412878                     /usr/lib/libattr.so.1.1.0
7fdc97904000-7fdc9790c000 r-xp 00000000 08:02 393041                     /usr/lib/libacl.so.1.1.0
7fdc9790c000-7fdc97b0b000 ---p 00008000 08:02 393041                     /usr/lib/libacl.so.1.1.0
7fdc97b0b000-7fdc97b0c000 r--p 00007000 08:02 393041                     /usr/lib/libacl.so.1.1.0
7fdc97b0c000-7fdc97b0d000 rw-p 00008000 08:02 393041                     /usr/lib/libacl.so.1.1.0
7fdc97b0d000-7fdc97d5a000 r-xp 00000000 08:02 446407                     /usr/lib/libcrypto.so.1.0.0
7fdc97d5a000-7fdc97f59000 ---p 0024d000 08:02 446407                     /usr/lib/libcrypto.so.1.0.0
7fdc97f59000-7fdc97f77000 r--p 0024c000 08:02 446407                     /usr/lib/libcrypto.so.1.0.0
7fdc97f77000-7fdc97f83000 rw-p 0026a000 08:02 446407                     /usr/lib/libcrypto.so.1.0.0
7fdc97f83000-7fdc97f87000 rw-p 00000000 00:00 0 
7fdc97f87000-7fdc97ff8000 r-xp 00000000 08:02 448884                     /usr/lib/libcurl.so.4.3.0
7fdc97ff8000-7fdc981f7000 ---p 00071000 08:02 448884                     /usr/lib/libcurl.so.4.3.0
7fdc981f7000-7fdc981f9000 r--p 00070000 08:02 448884                     /usr/lib/libcurl.so.4.3.0
7fdc981f9000-7fdc981fa000 rw-p 00072000 08:02 448884                     /usr/lib/libcurl.so.4.3.0
7fdc981fa000-7fdc981fb000 rw-p 00000000 00:00 0 
7fdc981fb000-7fdc98232000 r-xp 00000000 08:02 397473                     /usr/lib/libgpgme.so.11.13.2
7fdc98232000-7fdc98431000 ---p 00037000 08:02 397473                     /usr/lib/libgpgme.so.11.13.2
7fdc98431000-7fdc98432000 r--p 00036000 08:02 397473                     /usr/lib/libgpgme.so.11.13.2
7fdc98432000-7fdc98434000 rw-p 00037000 08:02 397473                     /usr/lib/libgpgme.so.11.13.2
7fdc98434000-7fdc985cd000 r-xp 00000000 08:02 407801                     /usr/lib/libc-2.21.so
7fdc985cd000-7fdc987cd000 ---p 00199000 08:02 407801                     /usr/lib/libc-2.21.so
7fdc987cd000-7fdc987d1000 r--p 00199000 08:02 407801                     /usr/lib/libc-2.21.so
7fdc987d1000-7fdc987d3000 rw-p 0019d000 08:02 407801                     /usr/lib/libc-2.21.so
7fdc987d3000-7fdc987d7000 rw-p 00000000 00:00 0 
7fdc987d7000-7fdc98875000 r-xp 00000000 08:02 414053                     /usr/lib/libarchive.so.13.1.2
7fdc98875000-7fdc98a75000 ---p 0009e000 08:02 414053                     /usr/lib/libarchive.so.13.1.2
7fdc98a75000-7fdc98a77000 r--p 0009e000 08:02 414053                     /usr/lib/libarchive.so.13.1.2
7fdc98a77000-7fdc98a79000 rw-p 000a0000 08:02 414053                     /usr/lib/libarchive.so.13.1.2
7fdc98a79000-7fdc98a7a000 rw-p 00000000 00:00 0 
7fdc98a7a000-7fdc98aaa000 r-xp 00000000 08:02 428654                     /usr/lib/libalpm.so.9.0.1
7fdc98aaa000-7fdc98caa000 ---p 00030000 08:02 428654                     /usr/lib/libalpm.so.9.0.1
7fdc98caa000-7fdc98cab000 rw-p 00030000 08:02 428654                     /usr/lib/libalpm.so.9.0.1
7fdc98cab000-7fdc98ccd000 r-xp 00000000 08:02 409736                     /usr/lib/ld-2.21.so
7fdc98d0c000-7fdc98e95000 r--p 00000000 08:02 661526                     /usr/lib/locale/locale-archive
7fdc98e95000-7fdc98ea3000 rw-p 00000000 00:00 0 
7fdc98ecb000-7fdc98ecc000 rw-p 00000000 00:00 0 
7fdc98ecc000-7fdc98ecd000 r--p 00021000 08:02 409736                     /usr/lib/ld-2.21.so
7fdc98ecd000-7fdc98ece000 rw-p 00022000 08:02 409736                     /usr/lib/ld-2.21.so
7fdc98ece000-7fdc98ecf000 rw-p 00000000 00:00 0 
7fffcd482000-7fffcd4a3000 rw-p 00000000 00:00 0                          [stack]
7fffcd59a000-7fffcd59c000 r--p 00000000 00:00 0                          [vvar]
7fffcd59c000-7fffcd59e000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by fosskers** [comment]
Definitely pacman. Aura1 sits on top of pacman without binding to libalpm directly, so if you see something like this it'll be a pacman issue.

**Comment by siddharthist** [comment]
This issue can probably be closed @fosskers

**Comment by fosskers** [comment]
You're right.
