### ISSUE TITLE
aura handling "provides" in build-deps

### ISSUE THREAD

**Issue by amosonn** [aurapm/aura#311]
When a package requires in build-deps a "virtual" package, provided by more than one package, aura chooses the first option available, instead of asking user.
Try removing both jdk7-openjdk and jdk8-openjdk, then build a package requiring java (such as jitsi). aura will choose jdk7-openjdk as builddep, regardless of which jre is installed.
Even worse, in this specific case, if jre8-openjdk is installed and default (per archlinux-java), build will fail, because after installing jdk7-openjdk, build will search for compiler in the java8 paths and fail to find it.

**Comment by fosskers** [comment]
Aura is currently bad at this, yes. Sorry for the late response.
