### ISSUE TITLE
Exit with success for `aura -Ayu` if no packages are being upgraded/updated

### ISSUE THREAD

**Issue by despairblue** [aurapm/aura#315]
First of, thanks for this great tool, I was looking for something that can automate package installs since _yaourt_ does not work as root at the moment, so I stumbled upon this amazing thing that does even more than I was actually looking for (having checkpoints with `-B` is simply genius :smiley:)

---

At the moment aura returns 1, though there is actually no error, its just that everything is up to date. That complicates scripting.

**Comment by koterpillar** [comment]
This has been raised as #299 but it seems that the fix hasn't been released anywhere. Bump?

**Comment by koterpillar** [comment]
Okay, #299 is fixed in 1.3.2.0 but this is still a problem.

**Comment by siddharthist** [comment]
Looks like [this section](https://github.com/aurapm/aura/blob/5599ac2cf7fbb681961f1b809b362a4be62d46e1/src/Aura/Commands/A.hs#L93-L94) warns the user that there is nothing to be done, but that [this line](https://github.com/aurapm/aura/blob/5599ac2cf7fbb681961f1b809b362a4be62d46e1/src/Aura/Commands/A.hs#L93-L96) sends an empty list to [`install`, which exits with failure](https://github.com/aurapm/aura/blob/5599ac2cf7fbb681961f1b809b362a4be62d46e1/src/Aura/Install.hs#L64). 

Possible solution: make the call to `install` part of the `else` case using a `do` block. I could make a PR for this if that's useful. 

Solution might be
