### ISSUE TITLE
Aura won't build with ghc 7.10.1

### ISSUE THREAD

**Issue by eazar001** [aurapm/aura#318]
A cabal install will halt on a conflict with the version constraints of `aur`.
```
(conflict: base==4.8.0.0/installed-fc6..., aur => base>=4.7 && <4.8)
```

**Comment by fosskers** [comment]
I see they've been updated in the repos. Thanks, I'll fix this.

**Comment by eazar001** [comment]
Thanks, just out of curiosity ... how is everyone else building? I feel oddly like that guy who's not "in the know". I usually set up a sandbox and cabal install aura. I'm curious how everyone else is installing `aura` right now. Is everyone just holding back on the previous version of ghc?

**Comment by fosskers** [comment]
The `aura` package is probably just breaking, and the `aura-bin` people don't notice a difference.

**Comment by eazar001** [comment]
I see, that would make a lot of sense.

**Comment by fosskers** [comment]
Update here: Aura also needs the `aur` package to build, which is failing right now because `wreq` is failing. Once `0.4` of wreq lands on Hackage this will work again.

**Comment by eazar001** [comment]
Yea, I tried to tweak the build earlier and noticed that it was breaking on `wreq`. I keep watch for the version bump. Thanks.

**Comment by fosskers** [comment]
[A few people are waiting on this.](https://github.com/bos/wreq/issues/61)

**Comment by fosskers** [comment]
Fixed on `aura1` branch.

**Comment by eazar001** [comment]
Thanks @fosskers I was starting get tired of using `yaourt` =]

**Comment by fosskers** [comment]
Do you build aura yourself or use the `aura` AUR package?

**Comment by eazar001** [comment]
_Usually_ I start a sandbox build the dependencies and then run `makepkg -si` inside the sandbox, so a bit of both. But for exceptional cases like this one .... I actually just cloned your repo and pulled the changes from the `aura1` branch, then sandboxed and built from there. So this time, I didn't use the AUR package.

**Comment by fosskers** [comment]
That reminds me, I went and made the AUR package `aura1-git` just for times like this.

**Comment by eazar001** [comment]
Hmm, interesting I've actually never tried the `aura1-git` package. I'll keep this in mind the next time I run into troublesome waters I guess. Thanks for the heads up!
