### ISSUE TITLE
ignoring pacman switch "--ignore"

### ISSUE THREAD

**Issue by amosonn** [aurapm/aura#320]
If I run
sudo aura -Syu --ignore <pkg_name>
and there is an upgrade for pkg_name, it will be added to the list of packages selected for upgrading, in contrast to the (wanted) behaviour of pacman
sudo pacman -Syu --ignore <pkg_name>
which will indeed issue a warning and remove pkg_name from the list.

**Comment by fosskers** [comment]
Aura's `--ignore` requires an argument. i.e.: `aura -S foo --ignore=bar`

Otherwise, `aura` respects the `IgnorePkg` field in `pacman.conf`.

**Comment by amosonn** [comment]
Sorry, my command in the previous post was somehow cut. The line I ran was
`sudo aura -Syu --ignore foo`
which is supported argument style under pacman. Perhaps the difference is in `--ignore=foo` vs. `--ignore foo`?

**Comment by amosonn** [comment]
Yep.
`sudo aura -Syu --ignore=foo`
does indeed ignore updates to foo, whereas
`sudo aura -Syu --ignore foo`
does not. pacman indeed accepts the second argument style as well.

**Comment by fosskers** [comment]
I think the particular arg-parsing library we're using doesn't allow the second style. Any free-floating arg like `foo` is considered a general argument and not a value for a flag.
