### ISSUE TITLE
Better aura -Qs error messages?

### ISSUE THREAD

**Issue by fhaust** [aurapm/aura#323]
I am not entirely sure that this is not a fault on my page, but it appears that the error messages from `aura -Qs` is not really helpful. When I search for a non-existing package aura replies with a "check your input" message:

```
# aura -Qs foobarbaz
aura >>= Please check your input.
```

Everytime this happens I wonder if I did a mistake in my query. `pacmans` behavior here is to return nothing as in "there is no result", which imho is not user friendly either, but is at least honest.

I see that `Please check your input` is the response to pacman failure. Maybe nothing can be done about this without changing pacman (which probably won't happen). So if this is true please consider this issue solved ... as in `won't fix`.

**Comment by fosskers** [comment]
You're right that this is confusing. This will fix itself when Aura2 comes out, as it won't rely on pacman at all.

**Comment by fhaust** [comment]
So much for shared code bases ;)

2015-05-04 20:06 GMT+02:00 Colin Woodbury <notifications@github.com>:
