### ISSUE TITLE
Possibility to install single package from bundle of ABS's PKGBUILD

### ISSUE THREAD

**Issue by forGGe** [aurapm/aura#324]
Here is the case:
I have vim package available via ABS. But unfortunately for me its PKGBUILD contains these lines:

```
pkgname=('vim-minimal' 'vim' 'vim-python3' 'gvim' 'gvim-python3' 'vim-runtime')
```

Well, I don't need ~~to build and~~ install neither gvim or vim-python3. I just want simple 'vim'.
~~For this purposes, `makepkg` introduces `--pkg` option.~~ _this wouldn't work if there are build dependencies inside bundle_

It would be awesome to see something like that in `aura` as well.

**Comment by fosskers** [comment]
Aura1 doesn't handle split packages very well.

I took a look at the `vim` PKGBUILD. For now I recommend some heavy use of `--hotedit` for it.

**Comment by forGGe** [comment]
Well, that's what I'm doing if I wish to install only one package from VIm bundle. I saw some other bundle packages and I think build-only-one solution is not viable.

How about install-only-one? Let them build together (especially if there any build dependencies exists inside one bundle), but install only one package. If you don't mind, I'm going to change issue description.

Your thoughts?
-- Max
-- Max

**Comment by fosskers** [comment]
Just tonight I fixed split package building. Right now I'm doing a build-all-install-all approach. Is that annoying?
