### ISSUE TITLE
-Cc should allow us to remove uninstalled packages

### ISSUE THREAD

**Issue by Jiehong** [aurapm/aura#325]
This is a feature request.

Currently, `-Cc n` allows aura to keep n versions of each package in the cache, including previously un-installed versions (as far as I can see).

It would be convenient to be able to remove all versions of uninstalled packages.

I propose the following option `-uninstalled/-u/-Cu`.

Documentation:

```
DOWNGRADE OPTIONS (-C)
    -u, --uninstalled
        Remove all uninstalled packages from the cache. You will be given a yes/no option before deleting anything.
```

Perhaps asking if the user wants to see the list of the target packages may be useful as well.

**Comment by fosskers** [comment]
I can see that being useful. It may be better as an Aura2 feature.
