### ISSUE TITLE
Implicit builduser without sudo

### ISSUE THREAD

**Issue by ahills** [aurapm/aura#326]
Automatically dropping privileges for makepkg when called via sudo is a great feature. On a system where the root user must frequently manage packages, it would be nice if the build user could be configured somewhere to eliminate the need to add it on the command line every time.

**Comment by fosskers** [comment]
A config file is planned for Aura2. In the meantime, you could make a shell alias that always includes the `--builduser` flag.

**Comment by ahills** [comment]
Yes, that's my current solution; it's just a bit unweildy to also distribute a .profile (or remember to create it) when deploying several installs. I will wait patiently for Aura2. Thanks.

**Comment by fosskers** [comment]
I know your pain!

**Comment by fosskers** [comment]
Is this still an issue for you?
