### ISSUE TITLE
Dependency package not correctly parsed

### ISSUE THREAD

**Issue by Jiehong** [aurapm/aura#328]
How to reproduce:

``` shell
$ sudo aura -A retroshare
aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `qt4[@]}[@]}[@]}` could not be found. You may need to search for a package to satisfy it.
```

However, the PKGBUILD of the package mentions `qt4` (https://aur.archlinux.org/packages/re/retroshare/PKGBUILD) but not the weird output Auras complains about.

**Comment by fosskers** [comment]
Yeah that's bash expansion magic which the current parser with never support. Aura2 to the rescue.

**Comment by theotherjimmy** [comment]
with the PR #364 should fix this.
My output with the new code is: 
```
aura >>= Determining dependencies...
aura >>= Repository dependencies:
libgnome-keyring
libmicrohttpd
libupnp
sqlcipher

aura >>= AUR Packages:
retroshare

aura >>= Continue? [Y/n]
```
