### ISSUE TITLE
Aur4

### ISSUE THREAD

**Issue by ramonsnir** [aurapm/aura#329]
Is Aura going to update to Aur4?

**Comment by flamusdiu** [comment]
@ramonsnir that's a given but not sure when. Aur3 will still be around for a while but most of the newer packages will be on the AUR4 domain for a few months then they are moved over.

**Comment by lightdot** [comment]
A few months is at least a bit vague if not incorrect. The grace period has already started.

This quote from the Arch Wiki explains it well:

>Current AUR maintainers are given a grace period between June 8th and July 8th to upload any package they already maintain to aur4.archlinux.org. After July 8th, any package in the current AUR can be taken over by any maintainer and uploaded. On August 8th, aur4.archlinux.org will become the new official AUR and will be moved to the aur subdomain.

So July 8th is the deadline, really, if the move is to be smooth and uneventful. About three weeks from now.

**Comment by leshow** [comment]
haskell-stack-git appears on aur4 but not on aur.archlinux. how do i build it properly with aura?

**Comment by flamusdiu** [comment]
@leshow well, some issues on the AUR4 page for it. But, you can do this

```
git clone https://aur4.archlinux.org/haskell-stack-git.git/
cd haskell-stack-git
makepkg -i
```

I guess that would work.

Or you can download the [source](https://aur4.archlinux.org/cgit/aur.git/snapshot/haskell-stack-git.tar.gz).

**Comment by leshow** [comment]
```2015-06-18 23:50:06 (470 KB/s) - ‘cabal.config’ saved [42306]

Removing stack constraint in the stackage snapshot
Downloading the latest package list from hackage.haskell.org
cleaning...
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: stack-0.0.3.1 (user goal)
next goal: path (dependency of stack-0.0.3.1)
rejecting: path-0.5.1 (global constraint requires ==0.5.0)
rejecting: path-0.5.0 (conflict: stack => path>=0.5.1)
rejecting: path-0.4.0, 0.3.0, 0.2.0, 0.1.0, 0.0.1, 0.0.0 (global constraint
requires ==0.5.0)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
==> ERROR: A failure occurred in prepare().
    Aborting...
2015-06-18 23:50:06 (470 KB/s) - ‘cabal.config’ saved [42306]

Removing stack constraint in the stackage snapshot
Downloading the latest package list from hackage.haskell.org
cleaning...
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: stack-0.0.3.1 (user goal)
next goal: path (dependency of stack-0.0.3.1)
rejecting: path-0.5.1 (global constraint requires ==0.5.0)
rejecting: path-0.5.0 (conflict: stack => path>=0.5.1)
rejecting: path-0.4.0, 0.3.0, 0.2.0, 0.1.0, 0.0.1, 0.0.0 (global constraint
requires ==0.5.0)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by justinkb** [comment]
aur4 should in fact be easier to use I suppose, so I do suggest implementing this asap

**Comment by flamusdiu** [comment]
@leshow that has nothing to do with AUR4; the package as issues as noted by the maintainer on the AUR4 page.

**Comment by fosskers** [comment]
Since we're on the topic, it might be helpful to take the `pandoc` approach to `aura1` builds and build it in a sandbox local to the build, which we wipe afterwards. That way we never have to worry about dependency hell.

I think most haskell devs on Arch use sandboxes anyway, so the Arch packages for them don't matter as much.

**Comment by flamusdiu** [comment]
@fosskers are you talking about something like this blog post: http://coldwa.st/e/blog/2013-08-20-Cabal-sandbox.html ?

**Comment by dkowis** [comment]
Is aur4 compatible with the existing aur? Like it's just API endpoint changes, or does this require actual work in this project (Just asking so I understand how much is required to get there.)

I'm already noting that several projects I want to use are in aur4, but not aur, and so I can't install them with my current aura :(

**Comment by fosskers** [comment]
@dkowis As far as I know they're mutually exclusive. Aura doesn't support AUR4 yet but it will soon.

**Comment by rmarquis** [comment]
@dkowis: Once AUR4 becomes the default on August 8, helpers should be able to use it the same way as the old AUR3 since it is backward compatible (URLPath field is kept, the RPCv3 interface is still there too).

**Comment by fosskers** [comment]
`aura` currently grabs package tarballs from a URL assumed from the package name. After August 8th, if the RPCv3 is still there, then things like `-Ai` or `-As` would still work, but package installation would not. Regardless the update needs to happen before that to handle the new git-style AUR.

**Comment by rmarquis** [comment]
Package name? Or do you mean package base? If you're dealing with split packages, you have no choice but use the PackageBase value.

Also, changes between the [RPCv3](https://aur.archlinux.org/rpc.php?type=info&arg=aura&v=3) and [RPCv4](https://aur4.archlinux.org/rpc.php?type=info&arg=aura&v=4) are minimal:
* removal of the category field,
* addition of the popularity field,

The URLPath field still exists, but its value has been modified to take into account changes done in AUR4. So if Aura is currently using it and you don't have the time to implement the new git clone/fetch style right now, aura will still work without issue by downloading the tarball as usual :)

**Comment by justinkb** [comment]
So, if I somehow make the the aur4 hostname refer to the aur ip address
(via some dns magic), I can (pseudo)migrate before August?

**Comment by rmarquis** [comment]
@justinkb: If Aura uses the URLPath RPC field to retrive the tarballs, then yes. Otherwise the code would need to be adapted.

**Comment by justinkb** [comment]
Any progress on this? I use aura mainly for the AUR functionalities and most package maintainers are no longer updating the aur PKGBUILDS (if that's even possible anymore...), just the aur4 ones. Getting kind of annoying to have to manually check and build all this stuff... That's the whole point of aura.

**Comment by flamusdiu** [comment]
@justinkb soon Aur4 will be switched to the Aur domain. When that ahppens, I don't know. I have do some limited testing changing my /etc/hosts to put aur4.archlinux.org to the same ip as the aur.archlinux.org site. Seems to work okay. You can always play with at.

**Comment by fosskers** [comment]
The AUR interaction library that Aura uses has been updated, and I'm tweaking aura to account for that on Sunday.

**Comment by flamusdiu** [comment]
@fosskers :+1:

**Comment by grazzolini** [comment]
The aur4.archlinux.org subdomain already is hosted on the same IP that aur.archlinux.org:

aur.archlinux.org has address 5.9.250.164
aur4.archlinux.org has address 5.9.250.164

So, unless there is some packet manipulation (iptables), if you change things on /etc/hosts, you'd still be talking to the old AUR, no matter what you do. I see that the aura-bin package on the old aur (aur.archlinux.org) is outdated compared with the package on aur4. So, just to confirm, since the interaction library has been updated, to upgrade the aura package we will need to manually download the PKGBUILD and create the package, right?

**Comment by bb010g** [comment]
The new AUR4 friendly `aura` and `aura-bin` are up on AUR4. @fosskers said he was putting the new `aura-bin` on AUR3, but it's not up yet.

**Comment by flamusdiu** [comment]
@grazzolini yeah, noticed that. =P different domains on the same hosts.

@bb010g yup, just have to wait around for it.

**Comment by bb010g** [comment]
You can also always `curl -O https://aur4.archlinux.org/cgit/aur.git/snapshot/aura-bin.tar.gz && tar -xzvf aura-bin.tar.gz && cd aura-bin && makepkg && sudo pacman -U aura-bin-1.3.2.0-1-x86_64.pkg.tar.xz`

**Comment by flamusdiu** [comment]
or in fish: `curl -O https://aur4.archlinux.org/cgit/aur.git/snapshot/aura-bin.tar.gz ;and tar -xzvf aura-bin.tar.gz ;and cd aura-bin ;and makepkg ;and sudo pacman -U aura-bin-1.3.2.0-1-x86_64.pkg.tar.xz` 

=P (yes this is what boredom does)

**Comment by bb010g** [comment]
_grumble grumble hipster fish users grumble grumble_

**Comment by flamusdiu** [comment]
=D :+1:

**Comment by fosskers** [comment]
High five for `fish`, @flamusdiu !

**Comment by fosskers** [comment]
`aura-bin-1.3.2.0` is now on AUR3, enjoy.

**Comment by g2p** [comment]
Is there a way to have aura build from aur4, prior to the switchover?

**Comment by fosskers** [comment]
It does right now, actually.
Am 01.08.2015 15:35 schrieb "Gabriel de Perthuis" <notifications@github.com
