### ISSUE TITLE
Unable to install xss-lock due to encoding related hGetContents fail

### ISSUE THREAD

**Issue by taruti** [aurapm/aura#330]
```
sudo aura -A  xss-lock
aura >>= Determining dependencies...
aura: fd:6: hGetContents: invalid argument (invalid byte sequence)
```

with AURA Version 1.3.0.5.

**Comment by fosskers** [comment]
This is an older bug, which I recall has to do with your locale settings.

**Comment by fosskers** [comment]
See [here](https://github.com/aurapm/aura/issues/78#issuecomment-22460726).

**Comment by fosskers** [comment]
Did you figure it out?

**Comment by taruti** [comment]
I did some locale magic that fixed it.

**Comment by fosskers** [comment]
Haha could you restate what said magic was?

**Comment by taruti** [comment]
It was 8 months ago sorry :(

**Comment by fosskers** [comment]
Ah ok, thanks.
