### ISSUE TITLE
Cannot get help on individual operations

### ISSUE THREAD

**Issue by bendavis78** [aurapm/aura#331]
The default --help message says to use --help or -h with an operation to get help on that specific operation. When I try this, I get this error: 

```
$ aura --help -A
aura >>= Conflicting flags given!
```

**Comment by flamusdiu** [comment]
@bendavis78 yeah, this has been an issue for me. However, until Aura2, I don't see a need for @fosskers to work on it since it's only a minor issue.

**Comment by fosskers** [comment]
Agreed. Aura2 will use `optparse-applicative` which is much nicer for parsing opts and displaying their help text.
