### ISSUE TITLE
error: only one operation may be used at a time

### ISSUE THREAD

**Issue by crodjer** [aurapm/aura#332]
I had tried aura a few months back, but after experimenting with it for a bit, I started receiving this error for ever (error: only one operation may be used at a time). I assume it is because of a residual lock file somewhere. Searching for the error string through the code doesn't provide me anything. I did find  one lockfile: `/var/lib/pacman/db.lck` in the code base, but I highly doubt it being an issue given pacman works fine and the lock file isn't present.

I re-visited aura to avoid an annoyance of `yaourt`, but this error, after months still exists. I suspect that it may also be something to do with `abs`, but haven't yet debugged much on that.

An example run:

```
$ sudo aura -SA utox-git
aura >>= Determining dependencies...
aura >>= Repository dependencies:
check
libconfig

aura >>= AUR Packages:
libfilteraudio-git
tox-git
utox-git

aura >>= Continue? [Y/n] Y
error: only one operation may be used at a time
```

**Comment by crodjer** [comment]
So this is embarrassing, the issue was the arguments I was passing. I had assumed that `-A` flag would make aura emulate `pacman` but for only for `aur` packages and I would need to pass the corresponding `pacman` actions. 

Sorry, I should have paid more attention to the man page.

**Comment by briceburg** [comment]
hilariously I ran into thisafter being away from aura for awhile. it would be more clear to immediately exit with `error: only one operation may be used at a time` instead of asking to continue and make you think something is wrong with the package being installed.

**Comment by fosskers** [comment]
Do you remember exactly what your input was? I'm curious to see exactly what was causing the problem. For the record, `error: blah` is an error at the pacman level, not Aura.

**Comment by briceburg** [comment]
My input was `aura -AS ltunify-git`  (and I dropped the S flag for the
install to work). Many thanks!

**Comment by fosskers** [comment]
Curious. I just discovered that `aura -QLi aura` works (it ignores the Q).

**Comment by Prijey** [comment]
> sudo pacman -S --upgrade
error: only one operation may be used at a time

**Comment by Prijey** [comment]
Hello everyone, I keep getting these errors, I would appreciate if you can help.
error: unresolvable package conflicts detected
 error: failed to prepare transaction (conflicting dependencies)
:: openbsd-netcat and gnu-netcat are in conflict

**Comment by fosskers** [comment]
@Prijey can you describe the exact command that you're running?
