### ISSUE TITLE
does not work without sudo

### ISSUE THREAD

**Issue by geratheon** [aurapm/aura#333]
Not really an issue but a problem I've run into: I can't use aura for my system because I dont have sudo installed and I really don't plan to change it; su does everything I need.

But it does not work with aura. When it tell's me to run it with sudo I can't just use su -c 'aura -Xyz', it insists on using sudo.

Is it possible to change this without having a big understandig of haskell?

**Comment by flamusdiu** [comment]
This is specifically for `aura -A` not for every `aura <flag>` because building can't be done as root (but a different user).

**Comment by flamusdiu** [comment]
On further testing: `su <non-root user> -c 'makepkg -i'` seems to work properly when installing packages through makepkg. However, as expected `su -c makepkg -i` fails.

**Comment by fosskers** [comment]
We need to rethink this process for Aura2. For now, we won't be fixing this in Aura1.
