### ISSUE TITLE
auto prompt for sudo

### ISSUE THREAD

**Issue by bitwave** [aurapm/aura#334]
yaourt has a unique way for prompting sudo, when using ´yaourt -Syu´

**Comment by flamusdiu** [comment]
`yaourt` wraps the command with `su` if `sudo` isn't installed from what I can tell.

**Comment by bitwave** [comment]
I mean, it would be awesome as normal user (not root), to use aura -Akua or aura -Syu, and then aura will prompt for your sudo password.

**Comment by fosskers** [comment]
For technical reasons this isn't possible.

**Comment by bitwave** [comment]
that's sad :(

**Comment by FSMaxB** [comment]
Actually this is technically possible (though ugly) by using a bash-wrapper that checks for 'A' and 'S' etc. as well as if the current user is root and then automatically calls `sudo aura ....`.

This isn't something that should go upstream, but you could put a little function in your bashrc to do that.

**Comment by flamusdiu** [comment]
@FSMaxB which is basically how `yaourt` works
