### ISSUE TITLE
Cannot decode byte

### ISSUE THREAD

**Issue by joca-bt** [aurapm/aura#340]
I am getting the following error when installing/upgrading some AUR packages with the new aura 1.3.2.0:
`aura: Cannot decode byte '\x6e': Data.Text.Internal.Encoding.streamDecodeUtf8With: Invalid UTF-8 stream`

Any ideas?

**Comment by joehillen** [comment]
@joca-bt which packages?

**Comment by joca-bt** [comment]
https://aur.archlinux.org/packages/evopop-gtk-theme-git/

**Comment by fosskers** [comment]
What do your locale settings look like?

**Comment by joca-bt** [comment]
```
/etc/locale.gen
en_GB.UTF-8 UTF-8
en_US.UTF-8 UTF-8
pt_PT.UTF-8 UTF-8
```

```
/etc/locale.conf
LANG=en_GB.UTF-8
LC_MONETARY=pt_PT.UTF-8
```

```
/etc/vconsole.conf
KEYMAP=pt-latin1
```

**Comment by fosskers** [comment]
That's very similar to what I have in my own files. Since it's `Data.Text` throwing the error, I wonder if it's a problem with the `aur` haskell package.

**Comment by fosskers** [comment]
`qemacs` is doing the same thing. I've put messages on the AUR pages of both those packages.

**Comment by fosskers** [comment]
Fix confirmed.
