### ISSUE TITLE
aws-cli package will not build unless makepkg output is unsuppressed

### ISSUE THREAD

**Issue by OwenTuz** [aurapm/aura#344]
I have found two packages (both from the same maintainer, so I would be inclined to suspect some unexpected behaviour in the PKGBUILD?) which build fine with makepkg but not with Aura:

https://aur.archlinux.org/packages/aws-cli/
https://aur.archlinux.org/packages/python-botocore/

On closer examination, the aws-cli package builds and installs as expected when installed with 'aura -Ax' but repeatably fails if the 'unsuppress' option is not included (I had already installed python-botocore manually when I found this so haven't tested that with the '-x' option).

The build appears to fail at the step 'python setup.py install'  in both cases.
Not a huge problem for me as there is a workaround, so feel free to close if you can't reproduce the problem.

Otherwise, please let me know if I can do anything else to test and/or troubleshoot.

Thanks,

Owen

**Comment by fosskers** [comment]
I'm seeing the same thing you are with `python-botocore`. I'm not sure yet what the cause is.

**Comment by rmarquis** [comment]
Looks like faulty PKGBUILDs. See https://github.com/rmarquis/pacaur/issues/357.

**Comment by fosskers** [comment]
Has the maintainer been contacted?

**Comment by OwenTuz** [comment]
Well spotted, thanks!

I can contact the maintainer and see about sorting that out. Will be a few
days minimum as I won't be near a computer, but that looks like a likely
candidate so I'd say you can close this as long as the above behaviour is
expected/considered reasonable.

Cheers,

Owen

Has the maintainer been contacted?

—
Reply to this email directly or view it on GitHub
<https://github.com/aurapm/aura/issues/344#issuecomment-133512366>.

**Comment by fosskers** [comment]
Please do, @OwenTuz

**Comment by OwenTuz** [comment]
Someone has already pointed this out to the maintainer - presumably one of you? Thanks if so. Closing as fixed.
