### ISSUE TITLE
/dev/random timeout (lack of entropy) causes misleading FailedConnectionException

### ISSUE THREAD

**Issue by Deewiant** [aurapm/aura#348]
I was puzzled for a short while tonight when trying to install any package resulted in a long wait followed by a `FailedConnectionException`:

```
$ sudo aura -Ax aura-bin
aura >>= Determining dependencies...
aura >>= AUR Packages:
aura-bin

aura >>= Continue? [Y/n] Y
aura >>= Building `aura-bin` ...
aura: FailedConnectionException "aur4.archlinux.org" 443
```

An `strace` invocation later I found that the problem was actually a timeout on `/dev/random`, not `aur4.archlinux.org`. Adding entropy to the system pool fixed the issue.

A less misleading error message would be appreciated. Although a better solution overall would be to rely on `/dev/urandom` or preferably `getrandom(2)` instead of `/dev/random`.

This might be a library problem, in which case I apologize for not looking into it enough to determine which library is at fault...

**Comment by jcelliott** [comment]
I'm seeing the same issue here.

**Comment by fosskers** [comment]
Aura uses `wreq` for HTTP calls and doesn't otherwise have any random elements. I imagine the dependance on `/dev/random` comes from encryption for https, which is unfortunately out of my control.

**Comment by anko** [comment]
Could one of you who has seen this happen [raise the issue with wreq](https://github.com/bos/wreq/issues) and ask for a better error?

**Comment by jcelliott** [comment]
bos/wreq#75

**Comment by fosskers** [comment]
Thanks guys.
