### ISSUE TITLE
aura claiming aur packages are not aur packages

### ISSUE THREAD

**Issue by klement** [aurapm/aura#350]
I noticed an issue with two packages. I've tried a couple of times, but the packages are not recognized as aur packages.

https://aur.archlinux.org/packages/jdk7-openjdk-infinality/
https://aur.archlinux.org/packages/jdk8-openjdk-infinality/

$ aura -A -s jdk | grep infinality
aur/jre7-openjdk-headless-infinality 7.u85_2.6.1-1 (21)
aur/jre7-openjdk-infinality 7.u85_2.6.1-1 (21)
aur/jdk7-openjdk-infinality 7.u85_2.6.1-1 (21)
aur/jre8-openjdk-headless-infinality 8.u60-1 (12)
    OpenJDK Java 8 headless runtime environment with infinality patch applied
aur/jre8-openjdk-infinality 8.u60-1 (12)
    OpenJDK Java 8 full runtime environment with infinality patch applied
aur/jdk8-openjdk-infinality 8.u60-1 (12)
    OpenJDK Java 8 development kit with infinality patch applied

$ sudo aura -A jdk7-openjdk-infinality jdk8-openjdk-infinality
aura >>= The following are not AUR packages:
jdk7-openjdk-infinality
jdk8-openjdk-infinality

**Comment by kyrylo** [comment]
I have the same issue with any package that I try to install with Aura. I install packages manually these days.

**Comment by mrak** [comment]
I had this problem and had to manually download and install the newest version of `aura`.

When it happened to me, the AUR had just switched over to the git-based aur4.

**Comment by klement** [comment]
I tried installing the same packages using wrapaur and got this:

$ wrapaur -a jdk8-openjdk-infinality
:: Checking Dependencies for jdk8-openjdk-infinality...
No dependencies found...
:: Downloading...
jdk8-openjdk-infinality
Cloning into '/home/<>/.wrapaur/jdk8-openjdk-infinality'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
:: Proceed with installation? [Y/n] y
installing jdk8-openjdk-infinality...
:: Edit PKGBUILD? [Y/n] y
/usr/bin/wrapaur: line 585: PKGBUILD: command not found
==> ERROR: PKGBUILD does not exist.
:: Remove source folder? [Y/n] y

so it seems that the problem is not in aura, but rather in the packages themselves..

**Comment by kyrylo** [comment]
Wow, is `<>` really your Linux username?

**Comment by klement** [comment]
sure, why not? :)

**Comment by fosskers** [comment]
```
colin@ko-linux ~> aura -Ai jdk7-openjdk-infinality
aura: Maybe.fromJust: Nothing
```
This is a package problem, yeah.

**Comment by kyrylo** [comment]
```
~% sudo aura -Ai jdk7-openjdk-infinality
Repository  : aur
Name        : jdk7-openjdk-infinality
Version     : 7.u85_2.6.1-1
AUR Status  : Up to Date
Maintainer  : trollixx
Project URL : http://icedtea.classpath.org
AUR URL     : https://aur.archlinux.org/packages.php?ID=219805
License     : custom
Votes       : 21
Description : OpenJDK Java 7 development kit

~% sudo aura -A jdk7-openjdk-infinality 
aura >>= The following are not AUR packages:
jdk7-openjdk-infinality

aura >>= Determining dependencies...
aura >>= Continue? [Y/n] y
```

**Comment by fosskers** [comment]
`1.2.2.0`? Current is `1.3.2.0`.

**Comment by kyrylo** [comment]
Oops :) I just updated Aura and I confirm that I see the same output as you.

**Comment by arteme** [comment]
Just got hit with this (using aura 1.3.4). None of the installed AUR packages are recognized.

```
slick ~ $ sudo aura -Ai dropbox
aura: Maybe.fromJust: Nothing
```

**Comment by pattop** [comment]
Same here:

patrick@gtr ~ % sudo aura -Ai google-chrome-beta
aura: Maybe.fromJust: Nothing

**Comment by GabLeRoux** [comment]
AURA Version 1.3.4
```
 sudo aura -Ayu
```
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 antergos is up to date                         0.0   B  0.00B/s 00:00 [----------------------------------------]   0%
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
atom-editor : 1.5.4-1 => 1.6.0-1
gitkraken : 0.8.3-1 => 0.9.2-1
numix-themes-git : 2.5.1.r129.c637d4d-1 => 2.5.1.r133.20c317a-1
unity-editor : 5.3.3f1+20160223-1 => 5.3.4f1+20160317-1

aura >>= The following are not AUR packages:
atom-editor
gitkraken
numix-themes-git
unity-editor

aura >>= No valid packages specified.
```

Searching for packages seems ok

```
sudo aura -As gimp-git
```
```
aur/gimp-git 1:2.9.2.137.g5c0f4b5-1 (67 / 1.36)
    GNU Image Manipulation Program
```

Can't install by specifying some packages
```
 sudo aura -A gimp-git
```
```
aura >>= The following are not AUR packages:
gimp-git

aura >>= No valid packages specified
```

Fetching informations doesn't seem to work anymore

```
sudo aura -Ai gimp-git
```
```
aura: Maybe.fromJust: Nothing
```

```
uname -a
```
```
Linux zbookarch 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux
```

Installing packages from Pacman using Aura seems to work tough (ie; `sudo aura -S gimp` works).

**Comment by v1kn** [comment]
Same here.  
Aura 1.3.4, Pacman 5.0.1  
`atom-editor-bin` , `mate-tweak-git` , `package-query` are not recognized

**Comment by Kironide** [comment]
I'm having the same issue with aura-bin-1.3.4-1. I reinstalled from https://github.com/aurapm/aura/issues/182#issuecomment-141109611 (I was already up to date beforehand) and it didn't fix my problems.

**Comment by GabLeRoux** [comment]
See #404, there's a workibg solution, but not quite sure it's the right way ;)

**Comment by joelostblom** [comment]
That workaround did not work for me with `purple-facebook`. Although yaourt is also having troubles with that package so maybe something else is wrong there...

**Comment by schoettl** [comment]
Same problem here. Many packages "are not AUR packages", including `aura`.

```
$ sudo aura -A aura
aura >>= The following are not AUR packages:
aura

aura >>= No valid packages specified.
```

```
aura 1.3.4
pacman 5.0.1
```

**Comment by afwlehmann** [comment]
Also here:
```bash
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
downgrade : 5.2.1-1 => 5.2.3-1
dropbox : 3.14.7-1 => 3.16.1-1
eclipse-jee : 4.5.1-1 => 4.5.2-1

aura >>= The following are not AUR packages:
downgrade
dropbox
eclipse-jee

aura >>= No valid packages specified.
```

**Comment by leshow** [comment]
All of my installed AUR packages are having the same issue

**Comment by fosskers** [comment]
Known issue, fixing now.

**Comment by reedobrien** [comment]
Thanks @fosskers for fixing this again in 654cfd7952ad0

And for anyone looking for how to update...
```
git clone https://aur.archlinux.org/aura-bin.git
cd aura-bin/
makepkg -sir
Aura -Ayu
```

**Comment by atondwal** [comment]
Huh, there's something more insidious as at play here:

```
$ aura -As namecoin-qt
aur/namecoin-qt 0.3.80-3 (7 | 0.20)
    Namecoin is a decentralized open source information registration and transfer system based on the Bitcoin cryptocurrency.
$ sudo aura -A namecoin-qt
aura >>= The following are not AUR packages:
namecoin-qt

aura >>= No valid packages specified.
$) sudo aura -A namecoin
aura >>= Determining dependencies...
aura >>= Repository dependencies:
qt5-tools

aura >>= AUR Packages:
namecoin

aura >>= Continue? [Y/n]
```

This is because the git URL is _different_ from the package name:
https://aur.archlinux.org/packages/namecoin-qt/

**Comment by bb010g** [comment]
`PackageBase` needs to be queried at some point in installation.

**Comment by fosskers** [comment]
Perhaps we're pulling the wrong value from the `AurInfo` that comes in from the `aur` library.

**Comment by v1kn** [comment]
Tried to install `paperwork` from the AUR today. for one of the depenencies, the error has returned. `python2-simplebayes` gets the *following are not AUR packages* message, even though aura sees it with `-As` flag

**Comment by fosskers** [comment]
Looking at the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-simplebayes), I think the `pkgname` field being an array is likely breaking Aura's bash parser.

**Comment by v1kn** [comment]
`neovim-git` recently introduced a new dependency: `lua51-mpack`. As in all above cases, package is searchable, but not installable (not AUR package error).  

It seems the issue has not been fully resolved. A definite fix is really needed. I see this issue is tagged `aura2` but imho this needs to be fixed much sooner. 
aura 1.3.6
