### ISSUE TITLE
Doesn't work with proxy correctly

### ISSUE THREAD

**Issue by madushan1000** [aurapm/aura#352]
It seems like the system defined proxy doesn't migrate to the package download level.
when I do something like "sudo -E aura -Ay mdm-display-manager" under proxy, the dependency packages from Arch repos download and install without a problem. But when aura tries to download the source pacages for mdm-display-manager over http or https the connection fails because the proxy is not set.

:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 infinality-bundle is up to date
aura >>= Determining dependencies...
aura >>= AUR Packages:
mdm-display-manager

aura >>= Continue? [Y/n] y
aura >>= Building `mdm-display-manager`...
aura >>= Well, building `mdm-display-manager` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
==> Making package: mdm-display-manager 2.0.4-1 (Tue Sep 22 09:03:06 IST 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading mdm-2.0.4.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0curl: (7) Failed to connect to github.com port 443: Connection timed out
==> ERROR: Failure while downloading mdm-2.0.4.zip
    Aborting...

aura >>= Would you like to continue anyway? [Y/n]

**Comment by fosskers** [comment]
How is your proxy set up?

**Comment by madushan1000** [comment]
HTTP_PROXY, HTTPS_PROXY environment variables

**Comment by fosskers** [comment]
Does this happen to you with all packages?

**Comment by madushan1000** [comment]
Yes, Both package download and package update are affected. When I use a non proxy connection. It works fine.

**Comment by archdria** [comment]
Proxy works for me by following these steps:
https://wiki.archlinux.org/index.php/Sudo#Environment_variables

**Comment by fosskers** [comment]
Thanks @archdria . @madushan1000 , can you confirm if that works for you?

**Comment by madushan1000** [comment]
Sorry, I can't test them. I no longer have my archlinux laptop. But as far as I remember, I tried those steps and it failed. Maybe a new version of aura fixed it?
