### ISSUE TITLE
Aura can't handle PKGBUILDs providing multiple packages

### ISSUE THREAD

**Issue by Ninja-Koala** [aurapm/aura#353]
PKGBUILDs providing multiple packages such as adwaita-qt gives me an:

```
aura >>= The following are not AUR packages:
adwaita-qt-common
```

Although the package is found in the search, and is provided by an PKGBUILD that is shared between adwaita-qt4, adwaita-qt5 and adwaita-qt-common

**Comment by flamusdiu** [comment]
It's split packages. Won't be completely fixed till 2.0

**Comment by jonnybarnes** [comment]
Is the [`libcurl-compat`](https://aur.archlinux.org/packages/libcurl-compat/) package an example of this?

**Comment by fosskers** [comment]
As far as I can tell from the PKGBUILD, it isn't.

**Comment by despairblue** [comment]
Same for [libappindicator-gtk2, libappindicator-gtk3, libappindicator-sharp](https://aur.archlinux.org/packages/libappindicator-gtk2/).

**Comment by fosskers** [comment]
Thanks.

**Comment by AlexTalker** [comment]
One more is [scst](https://aur.archlinux.org/packages/scst/).

**Comment by snyman** [comment]
Another example is the [Intellij IDEA](https://aur.archlinux.org/packages/intellij-idea-ultimate-edition/) packages. More interesting is [pasystray](https://aur.archlinux.org/packages/pasystray/), which actually provides two **conflicting** packages. Is 2.0 intended to handle an edge case like that?
