### ISSUE TITLE
-A doesn't seem to work anymore

### ISSUE THREAD

**Issue by parnmatt** [aurapm/aura#355]
Unsure why, but I can no longer seem in interact with the AUR with `aura`, with `-A`. e.g.,

- doesn't fully search; it returns some results but not all `-As`
- doesn't retrieve information about packages, even the ones it can search for, `-Ai`
- doesn't build: Failed to obtain build scripts

However I can interact with the standard repos, and local stuff.

(using aura-bin)

**Comment by flying-sheep** [comment]
having the same problem right now :flushed: 

```
sudo aura -A python-sphinxcontrib-newsfeed                                                                                                                                                    ⬆ ✱ ◼
aura >>= Determining dependencies...
aura >>= AUR Packages:
python-sphinxcontrib-newsfeed

aura >>= Continue? [Y/n] 
aura >>= Building `python-sphinxcontrib-newsfeed`...
aura >>= Well, building `python-sphinxcontrib-newsfeed` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
aura >>= Failed to obtain build scripts for `python-sphinxcontrib-newsfeed`.
aura >>= Would you like to continue anyway? [Y/n]
```

**Comment by bjin** [comment]
+1, failed to build any packages from AUR

**Comment by fosskers** [comment]
`aurweb` has updated, changing the API. The package `aur` that aura uses needs an update.

**Comment by fosskers** [comment]
The `OutOfDate` field has changed from a boolean value to either the date it went o.o.d, or `null`.

**Comment by fosskers** [comment]
I've updated the `aur` package. Going to change aura to work with it.

**Comment by fosskers** [comment]
Updated to `1.3.2.1` with the fix. You will probably have to install it manually.

**Comment by parnmatt** [comment]
:+1: Confirm rebuilt manually, fixed
