### ISSUE TITLE
Respect TTY presence in 'aura --version'

### ISSUE THREAD

**Issue by RomanSaveljev** [aurapm/aura#357]
This is merely a hint on how to comply with a typical adopted practice better. I have noticed calling `aura --version` draws a nice screen animation. Then immediately I tried:

```
aura --version | tee /tmp/f.log
```

The resulting `/tmp/f.log` is full of screen codes. If, for example, we look at `wget` (which uses terminal codes as well), then it handles it more gracefully:

```
$ wget http://ftp.nluug.nl/ftp/pub/os/Linux/distr/puppylinux/puppy-tahr/iso/tahrpup%20-6.0-CE/tahr-6.0-CE_noPAE.iso 2>&1 | tee /tmp/wget.log
$ head /tmp/wget.log
--2015-10-05 17:58:20--  http://ftp.nluug.nl/ftp/pub/os/Linux/distr/puppylinux/puppy-tahr/iso/tahrpup%20-6.0-CE/tahr-6.0-CE_noPAE.iso
Resolving ftp.nluug.nl (ftp.nluug.nl)... 192.87.102.43, 192.87.102.42, 2001:610:1:80aa:192:87:102:42, ...
Connecting to ftp.nluug.nl (ftp.nluug.nl)|192.87.102.43|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 208666624 (199M) [application/octet-stream]
Saving to: ‘tahr-6.0-CE_noPAE.iso.1’

     0K .......... .......... .......... .......... ..........  0%  393K 8m38s
    50K .......... .......... .......... .......... ..........  0%  389K 8m41s
   100K .......... .......... .......... .......... ..........  0%  753K 7m17s
```

Again, this is more like a cosmetic issue

**Comment by fosskers** [comment]
Similar issue when piping coloured Aura output. This has come up before in issue #102. It'll be fixed trivially in Aura2, where we'll be employing `extensible-effects` to have runtime evironment information available to all the text colouring functions.

**Comment by fosskers** [comment]
Fixed!
