### ISSUE TITLE
Aura isn't recognizing AUR packages at all

### ISSUE THREAD

**Issue by eazar001** [aurapm/aura#358]
```
[ebrahim@warmachine-alpha ~]$ aura -As linux-ck
[ebrahim@warmachine-alpha ~]$ 
[ebrahim@warmachine-alpha ~]$ aura -As swi-prolog-devel
[ebrahim@warmachine-alpha ~]$
```
As you can see I get absolutely no valid results. As expected, running an update will not attempt to build and install the new version of these packages. I installed the latest build of `aura` version 1.3.2.1. No results for me.

**Comment by fosskers** [comment]
You're on 1.3.2.1 and that's still happening?

**Comment by eazar001** [comment]
Yep. What I find strange is that it happened out of nowhere one day after a very long period of normal functionality. What I find even stranger is that nobody seems to be chiming in with similar cases. I wonder if there is something peculiar going on in my system. If there is, I can't see it.

**Comment by eazar001** [comment]
So while I notice that searching the repository for packages often pulls up no results, the searches that _do_ work seem to pull up results where all the package versions are highlighted in red (falsely suggesting that they are flagged out of date).

**Comment by eazar001** [comment]
Really ... nobody can confirm this?

**Comment by flamusdiu** [comment]
Appears to be working here ...

```
~> aura -As linux-ck
aur/linux-ck-headers 4.1.10-3 (289 / 6.85)
    Header files and scripts to build modules for linux-ck.
aur/linux-ck 4.1.10-3 (289 / 6.85)
    Linux Kernel with the ck2 patchset featuring the Brain Fuck Scheduler v0.464.
aur/nvidia-ck 355.11-3 (111 / 3.23)
    NVIDIA drivers for linux-ck.
aur/virtualbox-ck-host-modules 5.0.4-3 (38 / 1.70)
    Host kernel modules for VirtualBox running under Linux-ck.
aur/virtualbox-ck-guest-modules 5.0.4-3 (38 / 1.70)
    Guest kernel modules for VirtualBox running under Linux-ck.
aur/bbswitch-ck 0.8-12 (18 / 1.71)
    Kernel module allowing to switch dedicated graphics card on Optimus laptops for linux-ck
aur/broadcom-wl-ck 6.30.223.248-31 (12 / 0.01)
    Broadcom 802.11abgn hybrid Linux networking device driver for linux-ck.
aur/nvidia-340xx-ck 340.93-2 (6 / 0.40)
    NVIDIA drivers for linux-ck, 340xx legacy branch.
aur/nvidia-304xx-ck 304.128-2 (4 / 0.00)
    NVIDIA drivers for linux-ck, 304xx legacy branch.
aur/linux-ck-fbcondecor-headers 4.1.8-1 (1 / 0.00)
    Header files and scripts to build modules for linux-ck-fbcondecor.
aur/linux-ck-fbcondecor 4.1.8-1 (1 / 0.00)
    Linux Kernel with the ck2 patchset featuring the Brain Fuck Scheduler v0.464 and the fbcondecor framebuffer decoration support.
aur/bbswitch-lts-ck 0.8-30 (1 / 0.07)
    Kernel module allowing to switch dedicated graphics card on Optimus laptops for linux-ck
aur/bbswitch-ck-fbcondecor 0.8-8 (1 / 0.50)
    Kernel module allowing to switch dedicated graphics card on Optimus laptops for linux-ck
aur/acpi_call-ck 1.1.0-7 (1 / 0.48)
    A linux-ck kernel module that enables calls to ACPI methods through /proc/acpi/call
aur/nvidia-ck-fbcondecor 355.06-1 (0 / 0.00)
    NVIDIA drivers for linux-ck-fbcondecor.
aur/virtualbox-ck-fbcondecor-host-modules 4.3.20-4 (0 / 0.00)
    Host kernel modules for VirtualBox running under Linux-ck-fbcondecor.
aur/virtualbox-ck-fbcondecor-guest-modules 4.3.20-4 (0 / 0.00)
    Guest kernel modules for VirtualBox running under Linux-ck-fbcondecor.
```
```
~> aura -As swi-prolog-devel
aur/swi-prolog-devel 7.3.8-1 (8 / 0.04)
    Prolog environment (development version)
aur/swi-prolog-devel-git 7.3.8.r3.ge297584-1 (1 / 0.00)
    Prolog environment (latest git development version)
```
```
 __ _ _  _ _ _ __ _ 
/ _` | || | '_/ _` |
\__,_|\_,_|_| \__,_|
AURA Version 1.3.2.1
 by Colin Woodbury

Aura Translators:
 Chris "Kwpolska" Warrick (Polish)
 Denis Kasak / "stranac" (Croatian)
 Fredrik Haikarainen (Swedish)
 Lukas Niederbremer / Jonas Platte (German)
 Alejandro Gómez (Spanish)
 Henry "Ingvij" Kupty / Thiago "thiagowfx" Perrotta (Portuguese)
 Ma Jiehong / Fabien Dubosson (French)
 Kyrylo Silin (Russian)
 Bob Valantin (Italian)
 Filip Brcic (Serbian)
 "chinatsun" (Norwegian)
 "pak tua Greg" (Indonesia)
```

**Comment by eazar001** [comment]
I literally just cloned this repo, sandboxed it, and built all the packages manually, ... succeeded, and then ran aura on a search that duplicated this behavior. I'm wondering _what on Earth_ could be causing such a preposterous issue.

**Comment by bb010g** [comment]
Same thing. Also, even `-Aw` doesn't work. An build will start, but fail with `Failed to obtain build scripts for \`$package\`.

**Comment by eazar001** [comment]
@bb010g , so the latest `aura` is working fine for you then?

**Comment by bb010g** [comment]
Seems to be back to normal.

**Comment by eazar001** [comment]
Hmm, okay well this is pretty disheartening. I've no choice but to use packer or yaourt for now then. I'm going to miss the easy package downgrades the most. I just have no time to start debugging my package helper right now. Hopefully this issue will magically resolve for me by the next release =[

**Comment by fosskers** [comment]
@eazar001 sorry to hear this is happening for you. Have you tried `aura-bin`?

**Comment by eazar001** [comment]
@fosskers `aura-bin` isn't an option for me because I'm on a 32 bit system.

**Comment by bb010g** [comment]
Perhaps [stack](https://github.com/commercialhaskell/stack/blob/master/doc/install_and_upgrade.md) installing aura might work better? It would make sure things were clean at least.

**Comment by eazar001** [comment]
@bb010g , Well to be honest I haven't coded in Haskell in a few years; I thought that a sandbox would have been the cleanest approach possible. Unless you're implying there is something else that stack could offer (this is my first time hearing of stack). My problem is very strange; as you can see above, it is merely not printing anything. I'm not getting any errors/feedback at all. Some searches actually _do_ work, but they return dubious results like all packages registered as outdated. Very strange issue I'm having.

**Comment by eazar001** [comment]
FWIW, I even tried a fresh install using the latest GHC 7.10.2 (which forced me to start from a fresh package environment).
