### ISSUE TITLE
Popularity display

### ISSUE THREAD

**Issue by Jiehong** [aurapm/aura#359]
Hello,

Currently, votes and popularity values from AUR are displayed in aura as such:

```
(votes / popularity)
```

For example, `aura-bin` will have the following display (as of today): `(107 / 7.47)`.

I would like to argue that this also looks like a fraction, and it's a little bit confusing at first. I would like to offer some alternative to the slash as a separator, such as:

```
1. (107  -- 7.47)
2. (107 | 7.47)
3. (107 :: 7.47)
4. (107 ; 7.47)
```

I like the pipe one (second one).

What do you think about it?

**Comment by fosskers** [comment]
Thanks for bringing this up. I made it a `/` on a whim. I like the pipe or a single `:`.

**Comment by Jiehong** [comment]
I'm fine with both. As we won't make a survey about this, we leave it to you ;)

**Comment by fosskers** [comment]
`:` might seem like a ratio, which it isn't. Perhaps the pipe.

**Comment by rmarquis** [comment]
Note that cower implements it as ```(107, 7.47)``` similarly to a python tuple. Imho, it is a good way to show both votes and popularity without cluttering the display too much, while still using a delimiter that isn't confusing (disclaimer: I am the one that actually did implemented it).

**Comment by fosskers** [comment]
That saves 1 byte of whitespace, and a comma says "these are different items", meaning people shouldn't confuse them as a ratio.

**Comment by Jiehong** [comment]
But comma is also used as a decimal separator in some languages…

Pipe?

**Comment by bb010g** [comment]
Pipe works. It's a bit like the Haskell sum in data declarations. :P

**Comment by flamusdiu** [comment]
@Jiehong I think if it's done like a tuple ... using a comma wouldn't get confusing.

**Comment by Jiehong** [comment]
So, comma or pipe. Up to you @fosskers ;)

**Comment by fosskers** [comment]
Done.
