### ISSUE TITLE
I can't install `libcurl-compat`

### ISSUE THREAD

**Issue by jonnybarnes** [aurapm/aura#361]
I can't even find `libcurl-compat` in my search results. Which means I can’t update spotify. This is what happened:
```
aura >>= AUR Packages:
libcurl-compat
spotify

aura >>= Continue? [Y/n] 
aura >>= Building `libcurl-compat`...
aura >>= Well, building `libcurl-compat` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
aura >>= Failed to obtain build scripts for `libcurl-compat`.
aura >>= Would you like to continue anyway? [Y/n] 
aura >>= Building `spotify`...
aura >>= Well, building `spotify` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
==> Making package: spotify 1.0.15.137-1 (Thu 15 Oct 01:13:59 BST 2015)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> libcurl-compat
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```

**Comment by cortex** [comment]
I have the same problem, and in addition aura -Ax libcurl-compat gives no failure output:
sudo aura -Ax libcurl-compat
aura >>= Determining dependencies...
aura >>= AUR Packages:
libcurl-compat

aura >>= Continue? [Y/n] 
aura >>= Building `libcurl-compat`...
aura >>= Well, building `libcurl-compat` failed.
aura >>= Would you like to continue anyway? [Y/n] 

I have the same problem for other packages, for example qtpass. I don't know if it is just these, but these are the ones I tried.

For both of these, downloading the PKGBUILD and running makepkg works just fine.

**Comment by fosskers** [comment]
You both need to update to aura `1.3.2.1` and this should be fixed.

**Comment by jonnybarnes** [comment]
This has fixed the issue, thanks.
