### ISSUE TITLE
Aura fails to build virtualbox-ext-oracle

### ISSUE THREAD

**Issue by hutou** [aurapm/aura#362]
Package virtualbox-ext-oracle (virtualbox-ext-oracle-5.0.6-1) in AUR cannot be built, and I cannot know why ! Where is the output of "Dumping makepkg" ?

    $ sudo aura -A virtualbox-ext-oracle
    aura >>= Determining dependencies...
    aura >>= AUR Packages:
    virtualbox-ext-oracle
    
    aura >>= Continue? [Y/n] y
    aura >>= Building `virtualbox-ext-oracle`...
    aura >>= Well, building `virtualbox-ext-oracle` failed.
    aura >>= Dumping makepkg output in 3.. 2.. 1..
    aura >>= Failed to obtain build scripts for `virtualbox-ext-oracle`.
    aura >>= Would you like to continue anyway? [Y/n] n
    aura >>= Building failed.

Trying with the -x flag gives even less info !

    $ sudo aura -Ax virtualbox-ext-oracle
    aura >>= Determining dependencies...
    aura >>= AUR Packages:
    virtualbox-ext-oracle
    
    aura >>= Continue? [Y/n] y
    aura >>= Building `virtualbox-ext-oracle`...
    aura >>= Well, building `virtualbox-ext-oracle` failed.
    aura >>= Would you like to continue anyway? [Y/n] n
    aura >>= Building failed.

And building with yaourt is Ok !
Thanks.

**Comment by fosskers** [comment]
Just manually update aura to version `1.3.2.1` and you'll be fine.
