### ISSUE TITLE
[BUG] Aura doesn't detect and install dependencies from official repos.

### ISSUE THREAD

**Issue by trusktr** [aurapm/aura#365]
For example, I tries running this, and got errors:

```
┌─[13:44:04/hypership/trusktr/~]
└─╼ sudo -E aura -Aax --hotedit android-sdk android-sdk-platform-tools
[sudo] password for root:
aura >>= Determining dependencies...
aura >>= Would you like to edit the PKGBUILD of `android-sdk`? [Y/n] y
aura >>= Would you like to edit the PKGBUILD of `android-sdk-platform-tools`? [Y/n] n
aura >>= AUR Packages:
android-sdk
android-sdk-platform-tools

aura >>= Continue? [Y/n] y
aura >>= Building `android-sdk`...
==> Making package: android-sdk 24.3.4-2 (Wed Oct 21 13:45:24 PDT 2015)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> java-environment
  -> lib32-alsa-lib
  -> lib32-openal
  -> lib32-libstdc++5
  -> lib32-libxv
  -> lib32-mesa
  -> lib32-sdl
  -> lib32-fontconfig
  -> lib32-libpulse
  -> swt
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
aura >>= Well, building `android-sdk` failed.
aura >>= Would you like to continue anyway? [Y/n] n
aura >>= Building failed.
```

As you can see in the output, Aura is listing a bunch of dependencies as missing, instead of getting those dependencies. This is with `aura-bin` 1.3.2.1-1.

There are some other, probably related bugs, where, for example, the first time I ran the command, it didn't ask me to edit the PKGBUILD of android-sdk, it skipped it, then it skipped building android-sdk as well.

**Comment by fosskers** [comment]
What edits did you make to the PKGBUILD?

**Comment by trusktr** [comment]
I didn't edit any after inspecting them and seeing they looked good.

**Comment by PGPereira** [comment]
You have enabled the multilib repo?

**Comment by PGPereira** [comment]
But yeah, I can confirm the bug.
````
pedro@pedro ~ % env LANG=en_US.UTF-8 sudo -E aura -Aax --hotedit android-sdk android-sdk-platform-tools                                                                                     :(
aura >>= Determining dependencies...
aura >>= Would you like to edit the PKGBUILD of `android-sdk`? [Y/n] n     
aura >>= Would you like to edit the PKGBUILD of `android-sdk-platform-tools`? [Y/n] n
aura >>= AUR Packages:
android-sdk
android-sdk-platform-tools

aura >>= Continue? [Y/n] Y
aura >>= Building `android-sdk`...
==> Making package: android-sdk 24.4.1-1 (Sáb Out 24 00:29:42 BRST 2015)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> lib32-libstdc++5
  -> swt
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
aura >>= Well, building `android-sdk` failed.
aura >>= Would you like to continue anyway? [Y/n] Y
aura >>= Building `android-sdk-platform-tools`...
==> Making package: android-sdk-platform-tools r23.0.1-1 (Sáb Out 24 00:29:48 BRST 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading platform-tools_r23.0.1-linux.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2460k  100 2460k    0     0   757k      0  0:00:03  0:00:03 --:--:--  757k
  -> Found adb.service
  -> Found license.html
==> Validating source files with sha256sums...
    platform-tools_r23.0.1-linux.zip ... Passed
    adb.service ... Passed
    license.html ... Passed
==> Extracting sources...
  -> Extracting platform-tools_r23.0.1-linux.zip with bsdtar
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Purging unwanted files...
  -> Removing libtool files...
  -> Removing static library files...
  -> Compressing man and info pages...
  -> Stripping unneeded symbols from binaries and libraries...
==> Creating package "android-sdk-platform-tools"...
  -> Generating .PKGINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: android-sdk-platform-tools r23.0.1-1 (Sáb Out 24 00:29:56 BRST 2015)
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) android-sdk-platform-tools-r23.0.1-1

Total Installed Size:  9,54 MiB

:: Proceed with installation? [Y/n]

````

**Comment by fosskers** [comment]
`android-sdk` is using [a new way](https://wiki.archlinux.org/index.php/PKGBUILD#Dependencies) to name dependancy arrays in `PKGBUILD`s.

Aura's bash parser will have to be altered to account for this.

**Comment by lightdot** [comment]
Similar with libguestfs (updating to the previous version was fine, using aura 1.3.2.0):

    sudo aura -Akua
    [sudo] password for xxxxxxxx:
    aura >>= Fetching package information...
    aura >>= Comparing package versions...
    aura >>= AUR Packages to upgrade:
    libguestfs : 1.30.3-1 => 1.30.4-1

    aura >>= `libguestfs` PKGBUILD is up to date.
    aura >>= Determining dependencies...
    aura >>= AUR Packages:
    libguestfs

    aura >>= Continue? [Y/n]
    aura >>= Building `libguestfs`...
    aura >>= Well, building `libguestfs` failed.
    aura >>= Dumping makepkg output in 3.. 2.. 1..
    ==> Making package: libguestfs 1.30.4-1 (Tue Dec 15 18:23:53 CET 2015)
    ==> Checking runtime dependencies...
    ==> Checking buildtime dependencies...
    ==> Missing dependencies:
      -> gperf
      -> perl-string-shellquote
      -> perl-libintl-perl
      -> ocaml-findlib
      -> ocaml
    ==> ERROR: Could not resolve all dependencies.


    s aura -V
     __ _ _  _ _ _ __ _    Pacman v4.2.1 - libalpm v9.0.1
    / _` | || | '_/ _` |   Copyright (C) 2006-2014 Pacman Development Team
    \__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
    AURA Version 1.3.4

**Comment by fosskers** [comment]
Thanks guys, Aura 1.4 will fix all of this.

**Comment by vendion** [comment]
This doesn't seem to only happen with dependencies from the official repos.  I run into the same issue with [python3-xcpf](https://aur.archlinux.org/packages/python3-xcpf/) where `Aura` isn't picking up that [python3-memoizedb](https://aur.archlinux.org/packages/python3-memoizedb/) is a dependency that needs installed.

```
aura >>= Building `python3-xcpf`...
aura >>= Well, building `python3-xcpf` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
==> Making package: python3-xcpf 2015.12.19.2-2 (Thu Jan 14 06:27:10 EST 2016)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> python3-memoizedb
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.


aura >>= Would you like to continue anyway? [Y/n]
```

Looking at the PKGBUILD I don't see anything crazy going on in the depends array, looks normal to me minus quoting but that should just be style preference.  This is also with aura 1.3.4.

**Comment by erbridge** [comment]
Is there a workaround for dealing with this issue?

**Comment by fosskers** [comment]
I'm afraid not until we've moved to using `git` for our package downloads.

**Comment by erbridge** [comment]
The workaround that worked for me, was to `--hotedit` the `PKGBUILD` to just call the appropriate array `depends` and remove the other one.

**Comment by amosonn** [comment]
This time with makedepends, under `aura-bin-1.3.8-1`:
```
% sudo aura -Ax lib32-qt4
aura >>= Determining dependencies...
aura >>= AUR Packages:
lib32-qt4

aura >>= Continue? [Y/n] 
aura >>= Building `lib32-qt4`...
==> Making package: lib32-qt4 4.8.7-10 (Mon Mar 27 21:30:07 CEST 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> lib32-gtk2
  -> lib32-libcups
==> ERROR: Could not resolve all dependencies.

==> ERROR: An unknown error has occurred. Exiting...
aura >>= Well, building `lib32-qt4` failed.
```

**Comment by fosskers** [comment]
`android-sdk` does dep check properly now on `master`.
