### ISSUE TITLE
Error building without any diagnostics

### ISSUE THREAD

**Issue by khorser** [aurapm/aura#366]
Despite the `-x` option given, aura silently fails for some reason. Any way to debug?
```
sergey@afuji:~$ sudo aura -Ax gvim-hg
[sudo] password for sergey: 
aura >>= Determining dependencies...
aura >>= AUR Packages:
gvim-hg

aura >>= Continue? [Y/n] 
aura >>= Building `gvim-hg`...
aura >>= Well, building `gvim-hg` failed.
aura >>= Would you like to continue anyway? [Y/n] n
aura >>= Building failed.
```

Version information:
```
sergey@afuji:~$ aura --version
                       
 __ _ _  _ _ _ __ _    Pacman v4.2.1 - libalpm v9.0.1
/ _` | || | '_/ _` |   Copyright (C) 2006-2014 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 1.3.2.1   
 by Colin Woodbury     This program may be freely redistributed under
                       the terms of the GNU General Public License.
```

**Comment by fosskers** [comment]
Yeah, try building it with `makepkg` manually to see if the package is legit.

**Comment by khorser** [comment]
Hi, the package is ok, apparently aura cannot download the package for some reason:
```
sergey@afuji:~/temp$ aura -Awx swi-prolog-devel
aura >>= Downloading `swi-prolog-devel` source tarball...
sergey@afuji:~/temp$ aura -Awx gvim-hg
aura >>= Downloading `gvim-hg` source tarball...
sergey@afuji:~/temp$ ls
swi-prolog-devel.tar.gz
sergey@afuji:~/temp$ wget https://aur.archlinux.org/cgit/aur.git/snapshot/gvim-hg.tar.gz
--2015-10-25 08:50:18--  https://aur.archlinux.org/cgit/aur.git/snapshot/gvim-hg.tar.gz
Resolving aur.archlinux.org (aur.archlinux.org)... 5.9.250.164, 2a01:4f8:160:3033::2
Connecting to aur.archlinux.org (aur.archlinux.org)|5.9.250.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘gvim-hg.tar.gz’

gvim-hg.tar.gz                                           [ <=>                                                                                                                     ]   1.33K  --.-KB/s   in 0s     

2015-10-25 08:50:19 (70.3 MB/s) - ‘gvim-hg.tar.gz’ saved [1360]

sergey@afuji:~/temp$ ls
gvim-hg.tar.gz  swi-prolog-devel.tar.gz
```

**Comment by fosskers** [comment]
`aura -Aw gvim-hg` worked for me.

**Comment by koterpillar** [comment]
Same thing with `haskell-stack`:

```bash
$ sudo aura -A haskell-stack            
aura >>= Determining dependencies...
aura >>= AUR Packages:
haskell-stack

aura >>= Continue? [Y/n] y
aura >>= Building `haskell-stack`...
aura >>= Well, building `haskell-stack` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
aura >>= Failed to obtain build scripts for `haskell-stack`.
aura >>= Would you like to continue anyway? [Y/n] y
```

**Comment by koterpillar** [comment]
`aura -Aw haskell-stack` runs without error but I can't find any new files it downloads; nothing is changed in the current directory and the man page doesn't say where are they put.

**Comment by khorser** [comment]
@fosskers Are you saying you can see gvim-hg.tar.gz in the current directory after `aura -Aw gvim-hg`? If so are there any means to debug the issue further? For me the application reports success but no file apears.

**Comment by Libbum** [comment]
This seems to be a general error that is package independent. I can't seem to upgrade any packages (well, at least there is any indication that there are packages to upgrade):

```
$ sudo aura -Au
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= No AUR package upgrades necessary.
aura >>= No valid packages specified.
```

But, for example:
```
$ sudo aura -Li dropbox
Package        : dropbox
First Install  : [2015-10-17 09:56]
Upgrades       : 0
Recent Actions : 
 [2015-10-17 09:56] [ALPM] installed dropbox (3.10.7-1)

$ sudo aura -Ap dropbox
# Maintainer: Massimiliano Torromeo <massimiliano.torromeo@gmail.com>
# Contributor: Tom < tomgparchaur at gmail dot com >
# Contributor: David Manouchehri <d@32t.ca>

pkgname=dropbox
pkgver=3.10.8
...
```

For me also: `-Aw` doesn't get a tarball, and `-A` returns with `aura >>= Failed to obtain build scripts for 'dropbox'.`

Aura 1.3.2.1, Pacman 4.2.1, libalpm 9.0.1.

**Comment by fosskers** [comment]
`-Aw` downloads to the current directory. I'm still having none of the issues listed here, provided I use `1.3.2.1`.

**Comment by khorser** [comment]
Found an interesting thing: the binary package does not have the issue and it downloads all mentioned packages.

**Comment by Libbum** [comment]
Can confirm that the binary package (`aura-bin`) doesn't have these issues, it's the `aura` package only. Perhaps the missing `haskell-wreq` dependency fails silently and aura builds, but is required at this point and hence we get no information as to why nothing happens.

**Comment by fosskers** [comment]
Odd, considering I'm using the vanilla `aura` package.

**Comment by koterpillar** [comment]
I am using `aura-bin` and have this issue.

**Comment by fosskers** [comment]
I'm having this issue come up during some testing on an unrelated issue. It could be a problem with the `aur` package as found in the AUR.

**Comment by boomshroom** [comment]
I've been having this issue consistently. -Aw says that it's downloading, but the package doesn't appear in the current directory whether or not I have root.

**Comment by fosskers** [comment]
New `aura` and `aura-bin` released. Try them out, the problem should be fixed.

**Comment by boomshroom** [comment]
Nice. Installed the new version and now I have 19 updates.

**Comment by koterpillar** [comment]
Works for me with `haskell-stack`.

**Comment by fosskers** [comment]
Excellent, closing this.
