### ISSUE TITLE
`aura -As` and AUR website results differ

### ISSUE THREAD

**Issue by chookies** [aurapm/aura#368]
The search results for aura seems to differ from the [AUR website](https://aur.archlinux.org/).

When I search for intellij on the AUR website I get [the following results](https://aur.archlinux.org/packages/?O=0&K=intellij):

* android-studio
* intellij-idea-ce-eap
* intellij-idea-ue-eap
* intellij-idea-ultimate-edition

However, when I to the same query with Aura, only one result displays:

```
	→  aura -As intellij
aur/intellij-idea-ultimate-edition 14.1.5-1 (156)
    An intelligent IDE for Java, Groovy and other programming languages with advanced refactoring features intensely focused on developer productivity.
```

Any idea why?

```
	→  aura --version
 __ _ _  _ _ _ __ _    Pacman v4.2.1 - libalpm v9.0.1
/ _` | || | '_/ _` |   Copyright (C) 2006-2014 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 1.3.2.0   
 by Colin Woodbury     This program may be freely redistributed under
                       the terms of the GNU General Public License.
Aura Translators:      
...
```

**Comment by Possum** [comment]
I had the same issue - it seems to be fixed in the latest version (you'll have to install manually; installing the latest "aura-bin" package worked for me).

See also https://github.com/aurapm/aura/issues/355

**Comment by fosskers** [comment]
The `aur` haskell package (which aura needs) broke when the AUR changed recently. It's all fixed now with the latest `aura.`

**Comment by chookies** [comment]
That worked for me too, thanks!
