### ISSUE TITLE
Any chance I can get the PKGBUILD and auxiliary files of an old package install?

### ISSUE THREAD

**Issue by catalin-hritcu** [aurapm/aura#374]
Is there any chance I can get the `PKGBUILD` of a package already installed with Aura, but which is no longer available on AUR? I've tried `-Ap` but that seems to be pulling its information from AUR, so displays nothing in this case. Could it be that Aura saved the `PKGBUILD` it used somewhere locally and I can still access that?

In case you're wondering why I need this, here is the story: the `mintmenu` package was broken for a long while and the maintainer gave up and apparently even deleted the package (https://aur.archlinux.org/packages/mintmenu/ gives a 404 - Page Not Found error). In the meanwhile the upstream `mintmenu` developers tried to fix the issue, and are now asking if the fix worked (https://github.com/linuxmint/mintmenu/issues/137#issuecomment-154765274). However, without the old `PKGBUILD` to use as a start it's hard for me to try the upstream fix.

**Comment by flamusdiu** [comment]
See if the PKGBUILD is in `/var/cache/aura/pkgbuilds`

**Comment by catalin-hritcu** [comment]
It was indeed in `/var/cache/aura/pkgbuilds/mintmenu.pb`. Thanks a lot for the answer. Closing.

**Comment by flamusdiu** [comment]
Cool. Np. =)

**Comment by catalin-hritcu** [comment]
Seems, I was a bit too quick at claiming victory. The package needed a couple more files to work, one called mintmenu.install:
```
[hritcu@detained mintmenu]$ cp /var/cache/aura/pkgbuilds/mintmenu.pb PKGBUILD
[hritcu@detained mintmenu]$ makepkg   
==> ERROR: install file (mintmenu.install) does not exist or is not a regular file.
```
I managed to find those files all over the internets so I could get the package to build. Still wondering though, does Aura save those things as well?

**Comment by bb010g** [comment]
If it was in AURv3, ``git clone --depth=1 git://pkgbuild.com/aur-mirror.git``, as per [the Arch wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository#Git_repositories_for_AUR3_packages).

**Comment by catalin-hritcu** [comment]
This does it indeed (http://pkgbuild.com/git/aur-mirror.git/tree/mintmenu). Good to know for next time. Thanks a lot.
