### ISSUE TITLE
Error on AUR update

### ISSUE THREAD

**Issue by erbridge** [aurapm/aura#381]
This showed up in my terminal while attempting `aura -Auakx`:

```
aura >>= Fetching package information...
aura: TlsExceptionHostPort (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher")) "aur.archlinux.org" 443
```

I repeated the command immediately afterwards and it worked fine.

**Comment by fosskers** [comment]
This occurs at the `wreq` level (the lib we use for http calls). I have seen it before. Things like this should be caught.
