### ISSUE TITLE
No updates with -Ayu

### ISSUE THREAD

**Issue by xelra** [aurapm/aura#385]
Hello, 

I have a package `sonarr-develop` and the `PKGBUILD` has a `pkgver()` inside. Unfortunately when I run `aura -Ayu` it doesn't detect new versions and doesn't update the package. I have to manually check whether there is a new version and then force an update with `aura -A sonarr-develop`.

Does this have something to do with it not being a vcs package? How can I change that behavior?

**Comment by fosskers** [comment]
Any PKGBUILD weirdness will be fixed with Aura 1.4, which is currently under development.

**Comment by fosskers** [comment]
This should no longer be a problem on `master`, which will be released soon as Aura 2.0.
