### ISSUE TITLE
haskell-wreg missing in AUR

### ISSUE THREAD

**Issue by flamusdiu** [aurapm/aura#386]
@fosskers apparently, `haskell-wreq` is missing from AUR so https://aur.archlinux.org/pkgbase/aura/ isn't going to build properly.

**Comment by rmarquis** [comment]
This has been the case for a few months now. Aura doesn't build without a third party haskell repo.
The package ```haskell-lens-aeson``` seems also missing.

**Comment by fosskers** [comment]
Luckily we no longer depend on `wreq`.
