### ISSUE TITLE
Why the wait time before showing the build errors?

### ISSUE THREAD

**Issue by mbj** [aurapm/aura#389]
I wounder what is the reason for this behavior:

```
aura >>= Well, building `aws-cli` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
```

I'd prefer to show this errors immediately instead of having a 3 second brain pause?

OT: the build error is from a dependency that has to be installed manually before, not part of this issue.

**Comment by fosskers** [comment]
You're the first to bring this up. I'll add this to #377 .

**Comment by mbj** [comment]
@fosskers I try to optimize my workflow where I can, all types of "pause" simply get my brain bored and I might end up browsing the web instead of doing work. Hence I disabled all animations etc. So I also stumbled about this one.

Curious: Why was it added in the first place? To give background processes time to terminate?

**Comment by fosskers** [comment]
Given that that was put in in 2012, I can only speculate as to my motivations at the time. Likely it was "brace" the user for a flood of error messages.

**Comment by fosskers** [comment]
This pausing no longer happens.
