### ISSUE TITLE
Incorrect detection of package version from official repositories

### ISSUE THREAD

**Issue by tm45** [aurapm/aura#393]
There is a package "_icon-naming-utils_" which full version is **0.8.90-3**.
But aura says its version is "**-3**".

Here is output from terminal:

aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `icon-naming-utils` demands version `>=0.8.2`, but the most recent version is `-3`.

**Comment by fosskers** [comment]
This will fix itself with Aura 1.4, when we give up parsing the PKGBUILDs ourselves.

**Comment by fosskers** [comment]
This seems to no longer be a real package.
