### ISSUE TITLE
Special exit status when sudo is required

### ISSUE THREAD

**Issue by AladW** [aurapm/aura#394]
If an automatic sudo prompt isn't possible (#334), then aura should at least have a special exit code, rather than 1, when sudo is required. This way, you don't need to grep stderr or check for used arguments in bash wrappers.

**Comment by fosskers** [comment]
What's your use case?

**Comment by AladW** [comment]
Right now there's an ugly wrapper for people who expect automatic elevation from aura (as in pacaur and other helpers), from the ArchWiki:
```
function a(){
    AURA="$(aura "$@")"

    if echo "$AURA" | grep -q '^aura >>= .*You have to use `.*sudo.*` for that.*$'
    then
        sudo aura "$@"
    else
        echo "$AURA"
    fi
}
```
With an exit code of say 2, this could be reduced to:
```
function a() {
  aura "$@"
  (( $? = 2 )) && sudo aura "$@"
}

**Comment by AladW** [comment]
Looking at this again, grepping standard out really isn't reliable, unless you set LC_MESSAGES=C. See https://github.com/rmarquis/pacaur/issues/267
