### ISSUE TITLE
Include documentation on installing Aura

### ISSUE THREAD

**Issue by AladW** [aurapm/aura#395]
Right now the ArchWiki has some instructions, but you really should know how to install Aura from the included documentation. index.rst is mostly empty, would you be willing to take pull requests to expand on it?

**Comment by fosskers** [comment]
Yes, please. `stack` is currently the recommended method for developers.

**Comment by munyari** [comment]
@fosskers What is `stack`?

**Comment by fosskers** [comment]
http://docs.haskellstack.org/en/stable/README/
