### ISSUE TITLE
`aura -Br` does not restore

### ISSUE THREAD

**Issue by v1kn** [aurapm/aura#396]
Despite the fact that restoring package states have two variants: `-r` and `--restore`, only `--restore` works correctly. `sudo aura -Br` behaves just like `sudo aura -B`.  
By comparison, `-c` flag for cleaning packages states works as expected: `sudo aura -Bc` is equivalent to `sudo aura -B --clean`

**Comment by theotherjimmy** [comment]
This will likely be cleaned up when we switch to optparse-applicative in 1.4.

**Comment by v1kn** [comment]
OK, thanks

**Comment by fosskers** [comment]
Yes, the `-r` is likely being interpreted as a pacman flag mistakenly.

**Comment by HaleTom** [comment]
Can https://github.com/aurapm/aura/blob/master/aura/README.md be updated to show the `--restore` workaround in the meantime? (It currently shows `-Br`)

**Comment by fosskers** [comment]
@HaleTom done.

**Comment by fosskers** [comment]
I believe this is the offending line: https://github.com/aurapm/aura/blob/master/aura/src/Aura/Flags.hs#L209

**Comment by fosskers** [comment]
Yup:
```
colin@yumi ~/c/h/aura> stack exec -- sudo aura -Cb --auradebug
User              => root
True User         => colin
Build User        => colin
Using Sudo?       => Yes!
Pacman Flags      => 
Other Flags       => Cache Debug
Other Input       =>
...
```
^ Notice no `CacheBackup` flag was parsed.

**Comment by fosskers** [comment]
I've removed the short flags for these, and changed docs to reflect it. As mentioned above, this will probably fix itself when we move to `optparse-applicative`.
