### ISSUE TITLE
Feature suggestions for `aura -B`

### ISSUE THREAD

**Issue by v1kn** [aurapm/aura#397]
These are some suggestions of features that I miss, while using `aura -B`. I include all of them in a single issue in order not to spam. Please let me know if I should split them up into separate issues.
1. add package states list to the ouput of `aura -Bc`.  
   `aura -Bc 2` will clean all but last 2 packages states. However, it does not list available states in its output, so one has to run `aura -B --restore` and then cancel it to see how many states there are and figure out how many to remove.  
2. add a separate option for only listing packages states.  
   As of now canceling the `aura -B --restore` command is the only way to list the package states. there should be a separate flag imho.  
3. add a way to view package versions in each state.  
   If I want to roll back to a given package state, and have a lot of them, then there is the issue of not knowing which package state includes the desired package versions.
4. add an option to `-Bc` flag to be able to remove particular states non-chronologically, or to mark specific states as non-removable.  
   As of now, if I want to keep the first package state, I have to keep all of them. with say 15 states, there is no way to keep the first and last one. package state selection or marking as non-removable would make things much easier.

Thank You

**Comment by theotherjimmy** [comment]
Thanks for the suggestions!
We are currently working twards the 1.4 release, and will be changing the way options are parsed as part of that switch. If you would like to contribute these features yourself, I recommend that you wait for the optparse-applicative switch and then submit PR's against the aura-1.4 branch.

**Comment by v1kn** [comment]
I'd love to, but I am not a coder, so I can only ask for the suggestions to be considered in either aura 1.4 or 2.0. The best way I can contribute to projects is suggesting features, reporting bugs, testing out things and translation.

**Comment by fosskers** [comment]
Thanks a lot for these suggestions.

**Comment by fosskers** [comment]
Thanks @v1kn , I implemented (1), (2), and (4).
