### ISSUE TITLE
Dependency could not be found

### ISSUE THREAD

**Issue by parnmatt** [aurapm/aura#398]
`python2-joe` updated recently, and now requires `python2-git`.

`aura` cannot find the dependency, although `aura -As python2-git` lists it at the top.

Trying to get information `aura -Ai python2-git` returns a `aura: Maybe.fromJust: Nothing`

Searching for similar issues suggests that the PKGBUILD doesn't exists. However it does and it looks ok.

**Comment by theotherjimmy** [comment]
This is a Bash parser error. In 1.4 we will be switching to .SRCINFO parsing, and that will clean this up.

**Comment by fosskers** [comment]
`python2-joe` is defunct: https://aur.archlinux.org/packages/python2-joe/
