### ISSUE TITLE
Aura does not respect $EDITOR variable?

### ISSUE THREAD

**Issue by martinrotter** [aurapm/aura#399]
When I run
`EDITOR="/usr/bin/nano" sudo aura -A package --hotedit `
I am prompted for PKGBUILD edit, but not via nano. Vi is displayed instead.

Am I missing something?

**Comment by fosskers** [comment]
Yeah, you need to use `sudo -E` for that to work.

**Comment by martinrotter** [comment]
Oh, indeed. My bad. Closing. Thank you. :)
