### ISSUE TITLE
Some AUR packages use major.minor in pkgrel

### ISSUE THREAD

**Issue by biinari** [aurapm/aura#403]
According to the wiki entry, [`pkgrel`](https://wiki.archlinux.org/index.php/PKGBUILD#pkgrel) is allowed to take other formats like `major.minor`.

I have come across this in [teamviewer](https://aur.archlinux.org/packages/teamviewer) where the `pkgrel` is currently `2.3`. My installed version of teamviewer is the same version with `pkgrel=2.1` so aura does not consider there to be a new version available.

I am not sure whether this is an issue in aura or whether it ought to be solved by the teamviewer package maintainer by sticking to the more normal format of a single number.

**Comment by fosskers** [comment]
Aura 1.3.x is behind on this. Aura 1.4 will support this properly.

**Comment by biinari** [comment]
Great, sorry I hadn't peeked as far as Pull Requests yet to see it was already on the [1.4 roadmap](https://github.com/aurapm/aura/pull/377).

**Comment by fosskers** [comment]
No problem, hopefully we'll have this taken care of soon.

**Comment by fosskers** [comment]
This seems to no longer be an issue.
