### ISSUE TITLE
Aura isn’t updating my packages anymore

### ISSUE THREAD

**Issue by jonnybarnes** [aurapm/aura#404]
This is what happens:

```shell
╭─jonny@jonny-arch in ~ 
╰$ sudo aura -Akua
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
spotify : 1.0.23.93-2 => 1.0.25.127-1
tor-browser-en : 5.5.3-1 => 5.5.4-1

aura >>= The following are not AUR packages:
spotify
tor-browser-en

aura >>= No valid packages specified.
```

**Comment by neo1973** [comment]
I can confirm this, installing any package from the AUR is impossible. But the tool pbget is also unable to access PKGBUILDs from the AUR because of a problem with SSL. So maybe it isn't auras fault.

**Comment by koterpillar** [comment]
The AUR host name should be changed from `aur4.archlinux.org` to `aur.archlinux.org`.

**Comment by koterpillar** [comment]
Further information: I have built Aura from source, and while I cannot find `aur4` anywhere in the source, it still connects to `aur4.archlinux.org` as evidenced by `strace`.

**Comment by SShrike** [comment]
Can also confirm this is happening to me on Aura v1.3.4 w/ Pacman v5.0.1 and libalpm v10.0.1.

**Comment by emilio-aburto** [comment]
I can also confirm this happening. Subscribing so I can give info if needed.

**Comment by vendion** [comment]
I'm sure this may be redundant, but I can also confirm

```
[vendion@Baldr][~]% sudo aura -Akua
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
google-appengine-go : 1.9.31-1 => 1.9.34-1
google-cloud-sdk : 100.0.0-1 => 101.0.0-1

aura >>= The following are not AUR packages:
google-appengine-go
google-cloud-sdk

aura >>= No valid packages specified.
[vendion@Baldr][~]% _ aura -Aa google-appengine-go
aura >>= The following are not AUR packages:
google-appengine-go

aura >>= No valid packages specified.
```

Aura: 1.3.4
Pacman: 5.0.1
libalpm: 10.0.1

Digging further it seems this bug isn't Aura's fault, but a problem with the AUR Haskell package which Aura depends on.  [line 31 of Pkgbuild.hs of AUR packags](https://github.com/aurapm/haskell-aur/blob/f4e3f73bfffc2dcbc939acad7ba768d813ec68a6/Linux/Arch/Aur/Pkgbuild.hs#L31) hardcodes https://aur4.archlinux.org.

In case that really is the issue I filed a bug report upstream at https://github.com/aurapm/haskell-aur/issues/9

**Comment by skgsergio** [comment]
Same here. As @vendion says aura, or well haskell-aur, uses aur4.archlinux.org.

Yesterday Arch Linux changed their SSL certificates for the Let's encrypt ones and they didn't add aur4 to the certificate "alias" domains so there is a SSL certificate missmatch issue which seems to be the issue preventing aura from connecting to the server.

```
[*] Updating AUR packages
[>] sudo aura -Akua
[?] 	Run it? [Y/n] y
aura >>= Fetching package information...
aura >>= Comparing package versions...
aura >>= AUR Packages to upgrade:
pulseaudio-dlna : 0.4.7-1 => 0.5.0.1-1
pypy-setuptools : 1:20.2.2-1 => 1:20.3.1-1
pypy3-pip : 8.0.3-1 => 8.1.1-1
pypy3-setuptools : 1:20.2.2-1 => 1:20.3.1-1
rust-nightly-bin : 1.9.0_2016.03.15-1 => 1.9.0_2016.03.17-1
telegram-desktop-bin : 0.9.28-1 => 0.9.33-1

aura >>= The following are not AUR packages:
pulseaudio-dlna
pypy-setuptools
pypy3-pip
pypy3-setuptools
rust-nightly-bin
telegram-desktop-bin

aura >>= No valid packages specified.
[!] "sudo aura -Akua" failed with code 1
```

**Comment by Ninja-Koala** [comment]
As a dirty quick fix you can use:
`sudo sed -i 's/https:\/\/aur4.archlinux.org\//https:\/\/aur.archlinux.org\/\x00/' /usr/bin/aura`

It's fully working for me again now.

**Comment by adamczykm** [comment]
@Ninja-Koala thanks for the fix, works for me :)

**Comment by koterpillar** [comment]
Related: Aura should not be saying "such and such is not an AUR package" instead of the actual error message.

**Comment by johntyree** [comment]
@Ninja-Koala oh man... that is *nasty* :smiling_imp:

**Comment by dcbaker** [comment]
Why does aura hardcode the aur url in the source code anyway? Shouldn't that be in a configuration file so it doesn't need to be rebuilt when this sort of thing happens?

**Comment by fosskers** [comment]
It's hardcoded in the `aur` package, which I am fixing right now.

**Comment by fosskers** [comment]
Fixed and released, everyone.

**Comment by kgizdov** [comment]
I still can't get `aura -M` to work.

```bash
~ ❯ sudo aura -M aura-bin
aura >>= The following are not AUR packages:
aura-bin

aura >>= No valid packages specified.
```

**Comment by fosskers** [comment]
`aura-bin` isn't an ABS package, so `-M` would never work on it. You'll likely have to do a manual update with `makepkg` and `pacman -U` here.

**Comment by johntyree** [comment]
For what it's worth, the hacky binary patching mentioned above works well enough to do `aura -Akax aura-bin` and get back on the straight and narrow.
