### ISSUE TITLE
`/var/cache/aura/pkgbuilds` does not exist after building aura, causing errors

### ISSUE THREAD

**Issue by gatlin** [aurapm/aura#409]
First, I searched through the issues and couldn't find an instance of the operative keywords of the error in the issue tracker so please forgive me if this has been reported.

I pulled commit f06cf8e9a84a0ce8bf6f8505e151b6c46ca3edc4, and inside the directory ran

```
$> cabal sandbox init
$> cabal install --only-dependencies
$> cabal configure && cabal build
```

This built aura and I symlinked it to somewhere on my path. Worked great for searching and other querying. However, whenever I tried installing anything, I would get something similar to this:

```
$> sudo aura -A netatalk
[...]
aura: /var/cache/aura/pkgbuilds/netatalk.pb: openFile: does not exist (No such file or directory)
```

I fixed this by (as root) creating /var/cache/aura/pkgbuilds. I can look at the code and perhaps submit a pull request but I wanted to report this and see if anyone else had this issue. This is on a fresh Arch installation from today. I set up vim, git, and then pulled from master. So this is _not_ a complaint that an intermediate commit between releases had a bug, just that some kind of regression seems to be present in at least one case.

Or I'm a huge dumbass and I'll know why this is embarrassing soon enough. Either way, data!

**Comment by gatlin** [comment]
For the record, I'm installing it this way because aura is almost exactly what I've been looking for, but aura-bin has some bugs and running `makepkg` myself runs into the issue of some dependencies no longer being in the various Arch / Haskell repositories.

**Comment by fosskers** [comment]
Aura should check for the existence of that directory, and create it if it doesn't exist.
