### ISSUE TITLE
No AUR search results are being returned

### ISSUE THREAD

**Issue by jonnybarnes** [aurapm/aura#411]
I’m using aura version 1.3.5 with Pacman v5.0.1 and libpalpm v10.0.1

When I run the command `aura -As {term}` I get no output at all, no results, or error messages.

Full debug output if its helpful:

```shell
╭─jonny@jonny-arch in ~ 
╰$ aura --auradebug -As google
User              => jonny
True User         => jonny
Build User        => jonny
Using Sudo?       => No.
Pacman Flags      => 
Other Flags       => Debug AURInstall Search
Other Input       => google
Language          => English
Pacman Command    => pacman
Editor            => vim
$CARCH            => x86_64
Ignored Pkgs      => 
Build Path        => /mnt/storage/archive/pacman-cache/pkg/
Pkg Cache Path    => /mnt/storage/archive/pacman-cache/pkg/
Log File Path     => /var/log/pacman.log
Quiet?            => No.
Silent Building?  => Yes!
Must Confirm?     => Yes!
Needed only?      => No.
PKGBUILD editing? => No.
Diff PKGBUILDs?   => No.
Rebuild Devel?    => No.
Use Customizepkg? => No.
Forego PowerPill? => No.
Keep source?      => No.
╭─jonny@jonny-arch in ~ 
╰$ 
```

**Comment by fosskers** [comment]
Confirmed, I'm seeing the same thing.

**Comment by fosskers** [comment]
For some reason the AUR RPC is responding extremely slowly, even through a browser.

**Comment by fosskers** [comment]
Whether this happens is on-and-off. About 50% of calls to the RPC are taking a very long time, or they time out.

**Comment by fosskers** [comment]
We now suspect it to be an ipv6 vs ipv4 issue.

**Comment by gatlin** [comment]
Can confirm this also is the case on v1.3.6.

**Comment by fosskers** [comment]
Thanks, I'm still seeing it with 1.3.6 as well.

**Comment by jonnybarnes** [comment]
So is this a problem that can be fixed by aura, or is the problem upstream?

**Comment by v1kn** [comment]
I am having a similar issue, although not Sure if it is the same. 

 for `lightdm-gtk-greeter` , if i use the phrase *lightdm*, or *lightdm-*,  there are 0 returns.  Searching for *lightdm-gtk* will however return several results.

**Comment by maxfragg** [comment]
+1 and I can confirm, that it depends on the specificity of the query, exact package names seam to work always

**Comment by abougouffa** [comment]
I have the same issue with aura 1.3.6-1, Installed from the prebuilt AUR package **aura-bin**

**Comment by theotherjimmy** [comment]
fixed by #415. please re-open or submit a new issue if it's still a problem.

**Comment by jonnybarnes** [comment]
Any chance of a 1.3.7 release soon?

**Comment by fosskers** [comment]
@jonnybarnes Tomorrow afternoon.

**Comment by jonnybarnes** [comment]
Any chance of a pre-compiled binary being uploaded to the butbucket repo so that the arch aura-bin package can be updated?

**Comment by fosskers** [comment]
Yes, it's coming.
