### ISSUE TITLE
Feature: only install checkdepends (PKGBUILD) dependencies if check is to be run

### ISSUE THREAD

**Issue by quite** [aurapm/aura#412]
Could we have an options such as --nocheck which will make aura refrain from installing the PKGBUILDs checkdepends and try to run check(). Case in point: I don't want want vdirsyncer AUR to install all those dependencies to run all those tests...

**Comment by fosskers** [comment]
There seems to be enough call for a general `--makepkg-flags="..."` flag at the aura level. That said, is `check()` run by default?

**Comment by quite** [comment]
Ah, yeah... I realized that aura is of course using makepkg to actually build the AUR package. makepkg follows the `BUILDENV` in `/etc/makepkg.conf` and the default includes "check". So yes, `check()` is indeed run by default. _But,_ aura will install the packages listed in `checkdepends` in the `PKGBUILD`, even if `BUILDENV` doesn't include checking.

I would be happy if aura could infer whether makepkg will do checking or not, and if not then refrain from installing `checkdepends`. I guess a way to determine this is to actually read the correct makepkg.conf and examine `BUILDENV`. Tricky part is that makepkg.conf can be in different places and there are various overrides (`grep MAKEPKG_CONF /usr/bin/makepkg`). Could makepkg be provoked somehow to spit out `BUILDENV`...

**Comment by fosskers** [comment]
Resolving deps via `SRCINFO` as will be done in Aura 1.4 will fix this.

**Comment by fosskers** [comment]
Is this still an issue for you @quite ?
