### ISSUE TITLE
Unable to install AUR package just found

### ISSUE THREAD

**Issue by ranisalt** [aurapm/aura#416]
This is a rather strange thing, and I didn't find exactly the same issue. Aura seems unable to install an AUR package, claiming it's not on AUR, yet it just found the exactly same package on the previous command:

![http://i.imgur.com/IEpSkEs.png](http://i.imgur.com/IEpSkEs.png)

It happens with a lot of packages, not only this one, and this is rather annoying.

Edit: just as I posted, I searched a little more and found that #350 is exactly the same issue with the same packages, hahah sorry!

**Comment by theotherjimmy** [comment]
Closing duplicate
