### ISSUE TITLE
Unexpected behavior when passing -A and -S to aura at the same time.

### ISSUE THREAD

**Issue by dcbaker** [aurapm/aura#417]
Here's exactly what I did and what I got:

```
sudo aura -S python-requests -A python-git
aura >>= The following are not AUR packages:
python-requests

aura >>= Determining dependencies...
aura >>= AUR Packages:
python-git

aura >>= Continue? [Y/n] y
aura >>= Building `python-git`...
error: only one operation may be used at a time
```

It would be great if the error happened immediately, rather than doing the dependency handling and building the first pacakge (imagine if that was something that took hours to build, like chromium).

**Comment by fosskers** [comment]
Interesting, I'm surprised this isn't caught by the flag handling already. For the time being, if you successfully build something but the install step fails, you can install anything that's been built once from your cache with:

```console
sudo aura -C python-git
```
