### ISSUE TITLE
A failed AUR build with noconfirm results in a zero exit status

### ISSUE THREAD

**Issue by rien** [aurapm/aura#420]
Also, when an AUR package (for example `pacaur`) has a dependency that fails (for example `cower`) with the `--noconfirm` option, aura will still try to build `pacaur`, without success.

Is this intended behavior? When using aura in a script, I have to check with `aura -Qi foo` if the package was actually installed or not.

**Comment by fosskers** [comment]
Is this still an issue?

**Comment by fosskers** [comment]
When a fix for #501 goes through, we should be able to consider this completely fixed as well. Currently I believe the code on `master` would exit with `1` if there were such a failure.

> Also, when an AUR package...

I'm fairly sure this no longer happens.

**Comment by rien** [comment]
Since I don't use Arch anymore, this issue is not relevant for me anymore. Returning a nonzero exit status when a build fails is still best practice though, so thanks for looking into this :+1:
