### ISSUE TITLE
Permissions required message at odds with Pacman's

### ISSUE THREAD

**Issue by OJFord** [aurapm/aura#422]
```sh
$ aura -Sy foo
error: you cannot perform this operation unless you are root.
aura >>= Please check your input.
$ aura -Ay foo
aura >>= You have to use `sudo` for that.
$
```

The `-A` version's error is nicer to be honest - why have two lines when one will do - but would it not be better to match the Pacman output?

**Comment by bb010g** [comment]
Probably. Plus, you don't "have to" use `sudo`. `su` or whatever other root elevation tool you're using would work just fine. So something like this would probably be best:
```
$ aura -Ay foo
aura >>= You cannot perform this operation unless you are root.
```

**Comment by OJFord** [comment]
That sounds good, but still slightly annoying that they would differ in number of lines, and prefix.

Linking nvbn/thefuck#557 in case any changes here make that change redundant/require something new.

**Comment by fosskers** [comment]
Aura 1.x somewhat naively passes anything it detects as a pacman option straight down to pacman. `-A` is handled specially because it belongs to Aura.
