### ISSUE TITLE
Problem parsing dependencies, upgrade fails

### ISSUE THREAD

**Issue by nick-s-b** [aurapm/aura#430]
Quite often, when I try to update AUR packages with aura, I get this type of error:

```
....
aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `perl-gnome2-wnckperl-gtk2-imageviewperl-gtk2-uniqueperl-x11-protocol` could not be found. You may need to search for a package to satisfy it.
```

If I update with any other AUR manager, it works out just fine. In the example above, for some reason `aura` concatenated all these dependencies into one and it failed to find them. I've noticed this about every second or third time I try to upgrade using `aura`.

Anyone know what's wrong? Thanks!

**Comment by dpatti** [comment]
I started working on a fix for this, but then realized that there were a lot of inconsistencies in the way bash parsing is handled. I'll try to get a PR open with the specific fix for this. It has to do with the way `{foo,bar}` expansions work.

**Comment by nick-s-b** [comment]
@dpatti Thank you so much Doug! Much appreciated. Love `aura` and it pains me when I have to use something else.

**Comment by dpatti** [comment]
@nick-s-b Pull request submitted! If it wasn't clear: I'm not an aura maintainer, I just ran into the same bug as you and thought I could help. If you or anyone is willing to install [stack](https://docs.haskellstack.org/en/stable/README/), you can clone my branch and run `stack exec -- sudo aura -A whatever` while the pull request is waiting for review.

**Comment by fosskers** [comment]
@nick-s-b @dpatti Hi guys, could either of you provide some examples of packages whose deps concatenated in this way? I'd like to do some testing.

**Comment by dpatti** [comment]
@fosskers The one that I had an issue with (which looks like the same one here) is [`shutter`](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=shutter).

**Comment by fosskers** [comment]
Lots of expansion there. Let's see what happens.
