### ISSUE TITLE
Building shutter fails

### ISSUE THREAD

**Issue by simon04** [aurapm/aura#438]
Building the AUR package [shutter](https://aur.archlinux.org/packages/shutter/) fails:
```
$ sudo aura -A shutter
aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `perl-gnome2-wnckperl-gtk2-imageviewperl-gtk2-uniqueperl-x11-protocol` could not be found. You may need to search for a package to satisfy it.
```

Interestingly the individual dependencies are joined together to one big string of a dependency.

**Comment by fosskers** [comment]
Thanks for the report. The error you're seeing has been fixed and will be included in aura `1.3.8`.
