### ISSUE TITLE
aura does not find existing package

### ISSUE THREAD

**Issue by schoettl** [aurapm/aura#439]
aura fails to install the package `libgnome-data`.

```
$ sudo aura -A libgnome-data
aura >>= The following are not AUR packages:
libgnome-data

aura >>= No valid packages specified.
```

`libgnome` and `libgnome-data` are split packages and it seems to work with yaourt, see comments here:
https://aur.archlinux.org/packages/libgnome-data/

When I try to install `libgnome` directly, or another package that depends on `libgnome-data`, I get the following error:

```
$ sudo aura -A shutter
aura >>= Determining dependencies...
aura >>= Dependency checking failed for these reasons:
The dependency `libgnome-data` could not be found. You may need to search for a package to satisfy it.
```

**Comment by fosskers** [comment]
I noticed this problem over the weekend. Aura doesn't handle virtual packages very well at the moment. For the time being, I'd recommend installing `libgnome` manually.

**Comment by schoettl** [comment]
Ok thanks. Did you already fix it, or is there another issue addressing this problem?

**Comment by fosskers** [comment]
It isn't fixed yet unfortunately. This should be handled when we switch over to reading `SRCINFO`.
