### ISSUE TITLE
Allow more than one saved state per minute

### ISSUE THREAD

**Issue by HaleTom** [aurapm/aura#440]
It seems that the granularity of `-B` is the minute only:

 ```
@ravi@svelte:~$ date
Thu Feb 16 21:38:17 ICT 2017
@ravi@svelte:~$ sudo aura -B
aura >>= Saved package state.
@ravi@svelte:~$ sudo aura -B
aura >>= Saved package state.
@ravi@svelte:~$ sudo aura -B
aura >>= Saved package state.
@ravi@svelte:~$ sudo aura -B
aura >>= Saved package state.
@ravi@svelte:~$ sudo aura -B --restore
1. 2017.02(Feb).16.21.38
>>
```

In the above, expected to see 4 different saved states as `-B` was execute 4 times, but instead I only see one restore option.

For script usage or for speedy-gonzales sysadmins, can a number be appended if there is more than one saved state in a given minute?

**Comment by fosskers** [comment]
Interesting, you're the first to request this. Let me look into making the timestamps more granular.

**Comment by HaleTom** [comment]
Thanks for the fix! I guess it will be very unlikely to have a collision in a second, unless run from a script.
