### ISSUE TITLE
Say no restore points are available rather giving than obscure error

### ISSUE THREAD

**Issue by HaleTom** [aurapm/aura#441]
If I execute `-B --restore` when there are no saved states, I would expect a message like:
> aura: Error: no saved states exist to be restored. (Use bare -B to save current state)

Instead:

```@ravi@svelte:~$ sudo aura -Bc
aura >>= `0` package states will be kept. Remove the rest? [Y/n] y
@ravi@svelte:~$ sudo aura -B --restore
aura: /var/cache/aura/states: openFile: inappropriate type (is a directory)
@ravi@svelte:~[1]$ :
```

**Comment by fosskers** [comment]
Definitely a bug / oversight. Thanks for reporting this.

**Comment by fosskers** [comment]
This is a similar issue to the one reported about the `PKGBUILD` cache directory being non-existent before the first entry is written.
