### ISSUE TITLE
Use --reflink=auto to support btrfs

### ISSUE THREAD

**Issue by HaleTom** [aurapm/aura#443]
`btrfs` will not use additional disk space when files are copied with `cp --reflink=auto` (the disk blocks are shared between inodes until they are changed (copy on write)).

Would you consider using this to allow cache backups to consume negligible disk space?

**Comment by fosskers** [comment]
Sure, so long as it can be guaranteed that behaviour won't change on non-btrfs systems. 

PS. With Aura 1.3.8, make sure to use `aura -C --backup` instead of `-Cb`. It was the same issue as with `-Br`, where the flag wasn't being recognized.

**Comment by HaleTom** [comment]
`=auto` will reflink on `zfs` and `btrfs`, but will silently do nothing if reflinking is not supported by the underlying FS.

**Comment by fosskers** [comment]
Then this should be added. I'll keep you posted.

**Comment by fosskers** [comment]
Is this still a desired feature?

**Comment by HaleTom** [comment]
Sorry for missing this.

Yes, please add. Will save on disk usage.

**Comment by fosskers** [comment]
Done.

**Comment by HaleTom** [comment]
Cheers!

**Comment by HaleTom** [comment]
Cheers!
