### ISSUE TITLE
But I am root :)

### ISSUE THREAD

**Issue by catalin-hritcu** [aurapm/aura#448]
I know that aura doesn't work as root, only under sudo, but still sometimes the error message it gives out when called as root is completely hilarious ... and completely wrong:
```
[root@resurrected home]# aura -Akua
aura >>= You cannot perform this operation unless you are root.
[root@resurrected home]# 
[root@resurrected home]# whoami 
root
```

**Comment by fosskers** [comment]
Haha good catch... yes perhaps this should be changed.
