### ISSUE TITLE
How does the deprecation of ABS affect AURA?

### ISSUE THREAD

**Issue by jonnybarnes** [aurapm/aura#452]
See here: https://www.archlinux.org/news/deprecation-of-abs/

The abs package (which aura-bin at least depends on) has been removed, and the rsync endpoint will be closed at the end of the month.

**Comment by fosskers** [comment]
Thank you for catching this. We will have to rip out the `-M` operator and its functionality. Doing that will rid us of the `abs` dep until we can work around this.

**Comment by konfou** [comment]
>The `asp` tool, available in `[extra]`, provides similar functionality to `abs`. 
> `asp export pkgname` can be used as direct alternative

I suppose that part of [aura/src/Aura/Packages/ABS.hs](/aurapm/aura/blob/master/aura/src/Aura/Packages/ABS.hs) could be rewritten to using `asp` instead of `abs` and no lose of functionality.

**Comment by tyler274** [comment]
I personally like the functionality of abs in aura. Using asp seems like a good way forward.

**Comment by fosskers** [comment]
I'm not against reinstating it, but for now we'll have to rip it out to fix the dep conflict.

**Comment by fosskers** [comment]
Taken care of! `1.3.9` has been released, which disables `-M`.

**Comment by jonnybarnes** [comment]
I can’t update to v1.3.9 with aura-bin. It tries to download `https://github.com/aurapm/aura/releases/download/v1.3.9/aura-1.3.9-x86_64.tar.gz` which 404s. Looking at the releases tab on github the URL should be `https://github.com/aurapm/aura/releases/download/v1.3.9/aura-bin-1.3.9-x86_64.tar.gz`

**Comment by fosskers** [comment]
It's fixed now, I had uploaded the wrong file to GH.
