### ISSUE TITLE
db.lck is not released on exit with Ctrl+C (SIGINT)

### ISSUE THREAD

**Issue by Anton-Latukha** [aurapm/aura#455]
While Aura working or prompting an input, with Ctrl+C exit it does not release /var/lib/pacman/db.lck.
So lock should be removed manually every time.

It is very repeatable behaviour.

I use Ctrl+C extensively in my work. By POSIX, Ctrl+C sends SIGINT which is a soft signal, that asks to interrupt the process, so process can process to shutdown normally.

Aura example:
```
~> sudo aura -Syu
[sudo] password for user: 

...

Total Installed Size:  590.62 MiB
Net Upgrade Size:        1.42 MiB

:: Proceed with installation? [Y/n] ^C⏎

~> sudo aura -Syu
[sudo] password for user: 
LockError(/var/lib/pacman/db.lck): failed to lock database [[Errno 17] File exists: '/var/lib/pacman/db.lck']
aura >>= Please check your input.
````

**Comment by fosskers** [comment]
Thanks for reporting this. Currently the interaction between aura and pacman is brittle, but it won't be in Aura 2.

**Comment by Anton-Latukha** [comment]
Thank you.

**Comment by fosskers** [comment]
This no longer occurs on `master`, soon to be Aura 2.0.
