### ISSUE TITLE
Memory leak building purple-matrix-git package

### ISSUE THREAD

**Issue by dirtybytes** [aurapm/aura#456]
When updating a purple-matrix-git package with the "aura -Akuax --builduser=someuser" command, the output stops at the "determining dependencies..." stage, while the memory usage progressively increases until the system runs out of it (almost 6 GB of free memory + some swap storage is available). The package builds fine manually, and this problem was present with older versions of aura, too, as well as the most recent one.

**Comment by theotherjimmy** [comment]
Nice. Reproduced. I'll see what I can do about this.

**Comment by theotherjimmy** [comment]
Heh Resolved by #459 .

**Comment by fosskers** [comment]
Fix confirmed.
