### ISSUE TITLE
-M options not recognized by aura and then passed to pacman

### ISSUE THREAD

**Issue by vaurelios** [aurapm/aura#461]
Version:
```
 __ _ _  _ _ _ __ _ 
/ _` | || | '_/ _` |
\__,_|\_,_|_| \__,_|
AURA Version 1.3.9
 by Colin Woodbury
```

When i try to use `-M` options...

```
$ aura -Mt android-studio-canary
pacman: invalid option -- 'M'
aura >>= Please check your input.
```

**Comment by jakebailey** [comment]
`-M` got removed when the ABS tool was deprecated. @452

**Comment by 452** [comment]
@jakebailey good news)))

**Comment by jakebailey** [comment]
Sorry about that, forgot `#` was the right symbol to reference issues/PRs. Obviously my edit wasn't fast enough...

**Comment by vaurelios** [comment]
The `-M` still in `man` docs, should be removed too? And so in the Readme in this repo.

**Comment by fosskers** [comment]
Yes, the references to `-M` in the docs should be removed.
