### ISSUE TITLE
Feature request: Allow multiple AUR packages to be installed in bulk.

### ISSUE THREAD

**Issue by BurningSmile** [aurapm/aura#466]
I'd like to see a feature where I can specify a list of packages to be installed at once, and be asked if I want to install them only once at the begging rather than stooping at each individual package. The same idea could work with installing AUR packages individually as it's a pain to have to say yes to all of the grouped AUR dependencies.

**Comment by flamusdiu** [comment]
I would think using `--no-confirm` would fit that. i.e. `aura -A somepackage --no-confirm`

**Comment by fosskers** [comment]
This used to be the default behaviour, but changed some years ago when we changed how dependency solving works. @flamusdiu is right that `--no-confirm` can get around it.

**Comment by BurningSmile** [comment]
Okay, Thanks.

**Comment by fosskers** [comment]
This is coming: https://github.com/aurapm/aura/pull/483
