### ISSUE TITLE
aura not terminating when building some packages

### ISSUE THREAD

**Issue by frcl** [aurapm/aura#468]
When I try to install or update specific AUR packages aura just runs forever without consuming any system resources. Building the same packages with `makepkg` is a matter of seconds. I observed this with the packages `mypy` and `pipenv`, both python packages, but I have tested other python packages and they work fine. 

From `ps` output I can see that the `python setup.py install ...` command is executed. But it doesn't seem to actually do anything.

**Comment by naraesk** [comment]
I have the same problem with rssguards, strigi and qownnotes, although I don't know if they use python as well. aura does not terminate but with `makepkg` it worked as expected.

Strange workaround: Used `aura -xA` instead of `aura -A` and it worked.

**Comment by catalin-hritcu** [comment]
I'm also seeing such problems, for instance with `ocaml-menhir`. With `aura -A` it got stuck and didn't finish for 8 hours, with `git clone https://aur.archlinux.org/ocaml-menhir.git && cd ocaml-menhir && makepkg` it was almost instant.

**Comment by frcl** [comment]
I have tried `aura -xA` like @naraesk said and it works fine.

**Comment by catalin-hritcu** [comment]
Right, `aura -xA` works for me too.

**Comment by fosskers** [comment]
It must be something to do with how we're absorbing STDOUT when `-x` isn't provided.

**Comment by citral** [comment]
I have the same problem. Thanks for the `-xA` tip; it works for me, too.

**Comment by jasonhansel** [comment]
I seem to be having the same issues (with the `ffmpeg0.10` package); `-xA` fixes the problem.

**Comment by fosskers** [comment]
`-Ax` is the canonical ordering, but it doesn't really matter, functionality-wise.

**Comment by jonnybarnes** [comment]
The best pattern I can see myself, but I’ve not tested this systematically, is aura is only hanging like this on packages that need to be compiled. I’ve never seen it hang on a package that’s simply downloading and re-packaging a binary file (e.g. atom-editor-bin).

**Comment by fosskers** [comment]
`qownnotes` (mentioned above by @naraesk ) builds on `master` without issue now (invoked with a plain `-A`, not `-Ax`), so I'm going to close this issue.

**Comment by alathon** [comment]
I still have this problem on e.g., `dotnet-cli-git` package.

**Comment by fosskers** [comment]
`dotnet-cli-git` fails for me for a legitimate reason:
```text
...
[ 72%] Building C object System.Net.Http.Native/CMakeFiles/System.Net.Http.Native.dir/pal_versioninfo.c.o
[ 73%] Building C object System.Net.Http.Native/CMakeFiles/System.Net.Http.Native.dir/tmp/dotnet-cli-git-14597374745102149618/dotnet-cli-git/src/corefx-master/bin/obj/version.c.o
make[2]: *** No rule to make target '/usr/lib/libcurl-openssl-1.0.so', needed by 'System.Net.Http.Native/System.Net.Http.Native.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:370: System.Net.Http.Native/CMakeFiles/System.Net.Http.Native.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Failed to build corefx native components.
==> ERROR: A failure occurred in build().
    Aborting...
aura >>= Well, building `dotnet-cli-git` failed.
aura >>= There was a makepkg failure.
aura >>= Would you like to continue anyway? [Y/n] 
aura >>= Every package failed to build.
```

**Comment by Darnor** [comment]
Sorry for bringing this up again. I recently started trying out `aura` and some packages, mostly those that need to be compiled, still hang. The workaround using `aura -Ax` still does the trick though.

Sadly I forgot to write them all down, so I will just mention the last one I've encountered this issue, which is `ncurses5-compat-libs`. I'll update this comment, once I encounter others.

Hopefully someone can look into this.

**Comment by ollef** [comment]
This happens for me when building idnkit using aura 1.4.0.

**Comment by dancer69** [comment]
Is something changed? I tried to use -xA as suggested above, but I get error:
```
Invalid option -A

Did you mean one of these?
    -F
    -l
    -o
    -s
    -x
    -y
    -b
    -r
    -v
    -d
    -p
    -q
    -a
    -x
    -k
    -e
    -c
    -h`
```

**Comment by fosskers** [comment]
Yup `-Ax` is correct.
