### ISSUE TITLE
Removed VCS packages seem to crash Aura

### ISSUE THREAD

**Issue by mystfox** [aurapm/aura#469]
I don't know if that's exactly the case, and I can't test anymore, but it seems that trying to update a VCS package that is no longer on the AUR crashes aura, after it prints the `Determining dependencies...` line.

Specifically, I had vol-git installed, which seems to be removed from the aur. I tried to update everything with `sudo aura -Akuax --devel`, but that crashed with `aura: Prelude.head: empty list`, giving nothing else, even with `--auradebug`. I slowly updated packages 5-6 at a time, then, and only at the end, because I was going from the list of packages it said would be updated, did I figure that out. Sorry if this report isn't too helpful - I removed the package before thinking about that having it still could maybe help debug.

**Comment by fosskers** [comment]
Thanks for the report.

**Comment by fosskers** [comment]
Aura no longer has any `head` calls, and has more robust dependency checking (on `master` branch, soon to be Aura 2.0), so this shouldn't be a problem anymore.
