### ISSUE TITLE
Silently succeeds if there is no Internet connection.

### ISSUE THREAD

**Issue by kindaro** [aurapm/aura#498]
I have a flaky Internet connection. I was trying to install some packages from AUR and I was surprised when Aura silently did nothing. It took me a few moments to discover that my Internet connection went down.

#### Try it yourself:

    % aura -As aura-bin
    aur/aura-bin 1.4.0-1 (161 | 0.14)
        A secure package manager for Arch Linux and the AUR written in Haskell - Prebuilt binary
    % sudo netctl stop-all
    % aura -As aura-bin
    % echo $?
    0

#### Expected:

Aura should write an error message and return non-zero.

#### Actual:

Aura silently succeeds.

* * *

I am using Aura built from current `master` branch, commit `07e15e3` to be exact.

* * *

**P.S.** Overall, this is a great package, I am very happy about it, and very grateful to developers and maintainers.

**Comment by fosskers** [comment]
Here's a function within the code that makes calls to the AUR API:
```haskell
unwrap :: MonadIO m => Manager -> ClientM RPCResp -> m [AurInfo]
unwrap m r = liftIO . fmap (either (const []) _results) $ runClientM r (ClientEnv m url Nothing)
```
`runClientM` is *probably* catching some lower-level IO exception that's bubbling up from the failed internet connect, then returning it to me as an `Either`. Then the `either (const [])` is dumping that error in favour of just dumbly returning you an empty list. Hence the silent success.

**Comment by fosskers** [comment]
Done! You'll now see an error if Aura can't connect to the AUR.
