### ISSUE TITLE
`-Rns dpkg` weird error

### ISSUE THREAD

**Issue by kgizdov** [aurapm/aura#499]
as the title says, I get this:
```bash
$ sudo ~/.local/bin/aura -Rns dpkg
error: invalid option '--ignore'
aura >>= Please check your input.
```
`pacman` works fine when called directly

**Comment by fosskers** [comment]
Looks like you're using the current `master`?

**Comment by fosskers** [comment]
This is related: https://github.com/aurapm/aura/commit/2ccef64439e8df055b8b3acb0f60efa78bd8bada

**Comment by kgizdov** [comment]
pulled just now from `master`, cleaned the cache and rebuild, still see the error

**Comment by fosskers** [comment]
I know how to fix it, it'll be done today.

**Comment by fosskers** [comment]
I'm assuming you have some packages indicated in the `IgnorePkg` field of your `pacman.conf`?

**Comment by kgizdov** [comment]
yes, I am ignoring `lib32-glibc` if it matters

**Comment by fosskers** [comment]
There @kgizdov , that should do it.

**Comment by kgizdov** [comment]
works!
