### ISSUE TITLE
When makepkg fails, offer to explore the log.

### ISSUE THREAD

**Issue by kindaro** [aurapm/aura#501]
I thought Aura must be logging `makepkg`'s conversation, but I could not find anything about it in the man. _(There are many options, I may be missing something.)_ There is an option to review `pacman`'s log, but it is not `pacman`'s operation that ordinarily goes wrong, but `makepkg`'s.

For instance: I am trying to install `mingw-w64-glib2`. Along the process, some tarballs are pulled from gnu.org, and their signatures must be verified. But I would not have the right PGP keys. So, Aura will say: `There was a makepkg failure`. This is not helpful. I have to go dig the PKGFILE and see what key IDs it needs me to obtain.

But `makepkg` actually says it!

	% makepkg
	==> Making package: mingw-w64-pcre 8.42-1 (Mon 13 Aug 2018 10:27:33 PM +07)
	==> Checking runtime dependencies...
	==> Checking buildtime dependencies...
	==> Retrieving sources...
	  -> Downloading pcre-8.42.tar.bz2...
	** Resuming transfer from byte position 1404928
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
									 Dload  Upload   Total   Spent    Left  Speed
	100  161k  100  161k    0     0   7225      0  0:00:22  0:00:22 --:--:-- 12923
	  -> Downloading pcre-8.42.tar.bz2.sig...
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
									 Dload  Upload   Total   Spent    Left  Speed
	100   310  100   310    0     0     23      0  0:00:13  0:00:13 --:--:--    87
	==> Validating source files with md5sums...
		pcre-8.42.tar.bz2 ... Passed
		pcre-8.42.tar.bz2.sig ... Skipped
	==> Verifying source file signatures with gpg...
		pcre-8.42.tar.bz2 ... FAILED (unknown public key 9766E084FB0F43D8)
	==> ERROR: One or more PGP signatures could not be verified!

Perhaps `makepkg`'s output could be temporarily preserved, and an option to review it offered in case of failure?

**Comment by fosskers** [comment]
Sounds like you're using the version of Aura from the `master` branch? That's fine, just note that it represents v2.0 which isn't officially released yet. Either way, your experience is good bug testing for the project, so thank you.

Aura actually used to do what you're asking for. I can either reimplement that (it was lost during some major refactors) or you can use `-x` with `-A` for now. `-x` will unsuppress `makepkg` completely, so you'd see everything, including the errors.

**Comment by kindaro** [comment]
Yes, I cloned from here. Commit `07e15e3`.

The man actually documents the previous behaviour:

       -x, --unsuppress
           Unsuppress  makepkg output during building. By default this output is suppressed for a more silent
           install. Note that when this option isn't used, makepkg output is actually collected  and  printed
           if any errors occur.

Specifically, this phrase: _Note that when this option isn't used, makepkg output is actually collected  and  printed if any errors occur._

This is what I expected to be happening, too. I think it is a useful feature. It is filtering the signal _(output from erroneous invocations of `makepkg`, which is often of interest)_ from the noise _(output from successful invocations thereof, which is rarely of interest)_, based on an easily observable effect _(I assume that would be exit status)_, so it should be automated.

I see two ways to use `-x` with a use case similar to the one discussed here in mind:

1. Always run Aura with `-x` *"just in case"* something goes wrong.

  This would involve reading a lot of noise, while Aura is, praiseworthily, so nice and minimalistic.

2. Run Aura without `-x`, and re-run with `-x` when something does go wrong.

  This may possibly involve repeating some computation heavy, time consuming build steps.

I say both are less than optimal.

**Comment by fosskers** [comment]
Fair - I can reimplement the old behaviour.

**Comment by kindaro** [comment]
@fosskers If I may suggest, it is best to ask the user if they want to:

* **A.** Review the output of the erroneous `makepkg` invocation. That would lead to the old behaviour.
* **B.** Just leave. That would lead to the current behaviour.

It might be presented as a yes/no question.

**Comment by fosskers** [comment]
Yeah, I intend to prompt the user.

**Comment by fosskers** [comment]
@kindaro ^ that PR should do it.
