### ISSUE TITLE
Add labels to issues, such as "bug" "help wanted" "beginner friendly".

### ISSUE THREAD

**Issue by kindaro** [aurapm/aura#503]
For instance, consider #498 that I recently created. I do not have complete understanding of its status:
* Is it an acknowledged imperfection?
* If I make a pull request, will it be considered for merging?
* How complex does the hypothetical fix appear to be? A local change or an overarching overhaul?

If contributions are desirable, I believe some indication of issues that a prospective contributor may safely consider working on will significantly lower the entry barrier.

**Comment by fosskers** [comment]
Thanks! We do actually use labels actually. A few weeks ago I did a massive issue purge, and many of those were labeled. The ones that are left are admittedly in ambiguous territory. 

The top issues (yours included) will be solved soon, I know exactly how I want to approach them. #498 specifically is not rocket surgery, but I also wouldn't want a complete beginner tackling it. It's one of those "by the time I walked you through all the background information, I could have fixed it myself" things.

> If I make a pull request, will it be considered for merging?

PRs are pretty much always accepted, but we don't usually use labels for those.
