### ISSUE TITLE
Exist package could not be found

### ISSUE THREAD

**Issue by DarkNoys** [aurapm/aura#507]
When i try to install [libgnome-data](https://aur.archlinux.org/packages/libgnome/) aura write this:
```{bash}
$ sudo aura -Akax libgnome-data
aura >>= The following are not AUR packages:
libgnome-data

aura >>= No valid packages specified.
```
If i use yaourt all is well. 
I use latest release 1.4.0.

Wait v2.0 ?)

**Comment by fosskers** [comment]
This is already fixed on `master`, and 2.0 will be released very soon!
