### ISSUE TITLE
Undeclared dependency on non-empty-containers >= 0.1.2.0

### ISSUE THREAD

**Issue by nh2** [aurapm/aura#510]
The lower bound is too low.

https://github.com/aurapm/aura/blob/9652a3bff8c6a6586513282306b3ce6667318b00/aura/lib/Aura/Core.hs#L71

https://github.com/andrewthad/non-empty-containers/commit/694dae9ca49e3cb2dcd33534cdba2529bff50c6e

https://github.com/andrewthad/non-empty-containers/commit/2ff456939a18f5df9d6fd0bb0c8d4df6bf6eb53e#diff-a766c3db7ee49666e0f547aad31785abR6

**Comment by fosskers** [comment]
Fixed!

**Comment by fosskers** [comment]
I also fixed the bounds on Hackage with a `.cabal` revision.
