### ISSUE TITLE
Aura builds package twice

### ISSUE THREAD

**Issue by kloetzl** [aurapm/aura#521]
Here is something I have encountered a few times now. If Aura has to do a build that takes a looong time (eg. libc++) it will build it, install it and then starts building again. I tend to stop the second run with Ctrl+C. Checking with `pacman -Qi` shows that the correct version was installed

Btw, keep up the good work!

**Comment by fosskers** [comment]
What version of Aura are you using?

**Comment by kloetzl** [comment]
```
 __ _ _  _ _ _ __ _    Pacman v5.1.1 - libalpm v11.0.1
/ _` | || | '_/ _` |   Copyright (C) 2006-2018 Pacman Development Team
\__,_|\_,_|_| \__,_|   Copyright (C) 2002-2006 Judd Vinet
AURA Version 1.4.0     
```

Latest aura-bin, basically.

**Comment by fosskers** [comment]
This may already be fixed with `2.0.1`, the current version on `master`. Unfortunately I haven't released this to the AUR yet.

**Comment by kloetzl** [comment]
Ok, so I will close this issue for now and reopen it if the issue reappears with 2.x whenever that hits the the AUR.

**Comment by fosskers** [comment]
Great, let me know if anything else comes up.
