### ISSUE TITLE
Cache the built, though not installed, packages?

### ISSUE THREAD

**Issue by kindaro** [aurapm/aura#539]
It may sometimes happen that, after a long build, Aura _(or, rather, a subordinate Pacman)_ would ask: `Proceed with installation? [Y/n]`, and I would emphatically type a "y"... but it so happens that the keyboard was set to Greek. In an instant all the effort of the build system goes to ashes.

Surely it is not necessary to build the same code again.

## What I do:

    # sudo aura -A nix
    ...
    aura >>= Building `nix`...
    ...
    :: Proceed with installation? [Y/n] υ

## What I expect to happen:

When I restart, I am immediately offered to install `nix` as it is already built from the freshest source.

## What actually happens:

When I restart, the build starts over.

* * *

I use `AURA Version 1.4.0`, installed via `aura-bin` on Arch Linux.

**Comment by fosskers** [comment]
Do you have the means to test this with the current github `master`? The `aura-git` package on the AUR would also let you do this.

**Comment by kindaro** [comment]
As soon as I resolve some [build issues](https://github.com/commercialhaskell/stack/issues/4947)!

**Comment by fosskers** [comment]
> Cache the built, though not installed ...

This likely already happens on `master`. As of Aura 2 (released on Hackage but not the AUR), if Aura detects that the exactly version of the package you're trying to build is already in your package cache, it'll just use that. `--force` reperforms the whole build.

**Comment by kindaro** [comment]
That's great, I hope Aura 2 gets to the Aur soon.

**Comment by fosskers** [comment]
Soon, once I patch it a little bit more and finalize a new version.
