### ISSUE TITLE
Repository location

### ISSUE THREAD

**Issue by mb720** [aurapm/aura#550]
Hi and thanks a lot for Aura!

I'd like to know to which directory Aura checks out the repositories of installed software.

For example, when I install [tnef](https://aur.archlinux.org/packages/tnef/) using `aura -A tnef`, where on my file system does Aura check out the repository?

The reason I'd like to know this is to get the commit hash of the source code.

**Comment by fosskers** [comment]
It's the "build path" as set by runtime options, the default of which is:
```
defaultBuildDir :: Path Absolute
defaultBuildDir = fromAbsoluteFilePath "/tmp"
```
