### ISSUE TITLE
support --ignore on -Au

### ISSUE THREAD

**Issue by amosonn** [aurapm/aura#555]
Just like the `--ignore` flag for `-Su`, it would be useful to have one for `-Au`.

If there's interest, I could try and contribute on this, thought my Haskell is quite basic...

**Comment by fosskers** [comment]
`--ignore` should already work for `-A` as well.

**Comment by amosonn** [comment]
I remembered so as well, but I got:
```
[~]% sudo aura -Au --ignore abc     
aura >>= Conflicting flags given!
```
last time I tried.

**Comment by fosskers** [comment]
What's the output of `aura -V`?

**Comment by amosonn** [comment]
Sorry for not including this before.
1.4.0

**Comment by fosskers** [comment]
In that case we're good - this is already fixed on `master`.
